# SPDX-License-Identifier: GPL-2.0-or-later

top_srcdir		?= ../../..

include $(top_srcdir)/include/mk/env_pre.mk

INSTALL_TARGETS		:= generate_lvm_runfile.sh prepare_lvm.sh cleanup_lvm.sh

include $(top_srcdir)/include/mk/generic_trunk_target.mk
