# Copyright (c) 2019 - Linaro Limited. All rights reserved.
# SPDX-License-Identifier: GPL-2.0-or-later

top_srcdir		?= ../../../..

include $(top_srcdir)/include/mk/testcases.mk

LDLIBS+=-lrt

include $(top_srcdir)/include/mk/generic_leaf_target.mk