=head1 NAME

hpiel - An openhpi sample application that displays HPI event log entries. 

=head1 SYNOPSIS 

hpiel [ -d -e -c -p -r -x -v -h ]

=head1 DESCRIPTION

hpiel searches the RPT (Resource Present Table) for resources with SAHPI_CAPABILITY_EVENT_LOG and displays event log entries for resources found.

=head1 OPTIONS

=over 2

 --del, -d				display domain event log entries 
 --entitypath="<arg>", -e "<arg>"	display resource event log entries
                                        (e.g. -e "{SYSTEM_CHASSIS,2}{SBC_BLADE,5}")
 --clear, -c	clear log before reading event log entries
 --resource, -p	pull resource info along with log entry
 --rdr, -r	pull RDR info along with log entry
 --xml, -x	print output in xml format (not implemented)
 --verbose, -v	print debug messages
 --help, -h	print this usage message

 If neither -d or -e "<arg>" are specified, event log entries will be shown
for all supporting resources by default.

=back

=head1 HPI APIs uniquely used in this application 

=over 2

SaErrorT SAHPI_API saHpiEventLogInfoGet (
    SAHPI_IN  SaHpiSessionIdT     SessionId,
    SAHPI_IN  SaHpiResourceIdT    ResourceId,
    SAHPI_OUT SaHpiEventLogInfoT  *Info
);

SaErrorT SAHPI_API saHpiEventLogEntryGet (
    SAHPI_IN    SaHpiSessionIdT          SessionId,
    SAHPI_IN    SaHpiResourceIdT         ResourceId,
    SAHPI_IN    SaHpiEventLogEntryIdT    EntryId,
    SAHPI_OUT   SaHpiEventLogEntryIdT    *PrevEntryId,
    SAHPI_OUT   SaHpiEventLogEntryIdT    *NextEntryId,
    SAHPI_OUT   SaHpiEventLogEntryT      *EventLogEntry,
    SAHPI_INOUT SaHpiRdrT                *Rdr,
    SAHPI_INOUT SaHpiRptEntryT           *RptEntry
);

SaErrorT SAHPI_API saHpiEventLogClear (
    SAHPI_IN  SaHpiSessionIdT     SessionId,
    SAHPI_IN  SaHpiResourceIdT    ResourceId
);

=back

=head1 SEE ALSO

=head1 AUTHORS

Authors of this man page:

 Peter D Phan (pdphan@users.sourceforge.net)

