=head1 NAME

hpifan - An openhpi sample application that shows "Fan Control" management instruments

=head1 SYNOPSIS 

hpifan [-h] [-s fan_speed_level]

=head1 DESCRIPTION

hpifan walks the RPT (Resource Present Table) for resouces that have 
"Fan Control" management instruments (SAHPI_CTRL_FAN_SPEED).


=head1 OPTIONS

=over 2

 -h          help
 -s <speed>  set fan speed for ALL fans

=back

=head1 SEE ALSO

 
=head1 AUTHORS

Authors of this man page:

 Peter D Phan (pdphan@users.sourceforge.net)

