=head1 NAME

hpiinv - An openhpi sample application that shows resources' inventory records. 

=head1 SYNOPSIS 

hpiinv [-x] [-a asset_tag]

=head1 DESCRIPTION

hpiinv walks the RPT (Resource Present Table) looking for resources that have Inventory Capability.  It displays all inventory records found.  

=head1 OPTIONS

=over 2

 -a  Sets the asset tag
 -x  Display debug messages
 -z  Display extra debug messages

=back

=head1 ENVIRONMENT VARIABLES

For generic OpenHPI, there is *no* additional environment variable required.
For some devices; sahalee, mBMC; BMCONLY flag needs to be set for additional device characterization based on rdr.IdString.Data.

=over 2
BMCONLY
LENGTH_BAD

=back

=head1 SEE ALSO

=head1 AUTHORS

Authors of this man page:

 Peter D Phan (pdphan@users.sourceforge.net)

