=head1 NAME

hpionIBMblade - An openhpi sample application that shows how two (2) openhpi plugins can be used to display and manage resources of an IBM Blade with Basedboard Management Controller (BMC).

=head1 SYNOPSIS 

hpionIBMblade [ -x ]


=head1 DESCRIPTION

 hpionIBMblade shows how two (2) openhpi plugins can be used to display  
and manage resources of an IBM Blade with Basedboard Management Controller (BMC).
 
 Both the ipmi and snmp_bc plugin have the same IBM Blade target.  Resources from
both plugins are combined to show a complete view of the IBM Blade.  
   
 @@ WARNING @@ RESTRICTIONS @@ WARNING @@ RESTRICTIONS @@ WARNING @@ RESTRICTIONS @@
 
 This client application is designed to run **only** inband on an IBM Blade with Basedboard
Management Controller (BMC) 

=head1 OPTIONS

=over 2

-x  Display debug messages.

=back

=head1 SAMPLE CONFIGURATION FILE

    handler libipmi        {
        entity_root = "{SYSTEM_CHASSIS,2}"
        name = "smi"
        addr = 0
    }

    handler libsnmp_bc {
        host = "bc.mm.ip.address"
        version = "3"
        community = "bc_community"
        entity_root = "{SYSTEM_CHASSIS,1}"
        security_name = "myid"
        passphrase = "mypassword"
        security_level = "authNoPriv"
        auth_type = "MD5" 
    }


=head1 SEE ALSO


=head1 AUTHORS

Authors of this man page:

 Peter D Phan (pdphan@users.sourceforge.net)

