=head1 NAME

hpisettime - This sample openhpi application excercises Event Log clock APIs. 

=head1 SYNOPSIS 

hpisettime -d mm/dd/yyyy -t HH:MM:SS [-x]

=head1 DESCRIPTION

hpisettime sets new date and time for the Event Log clock.

=head1 OPTIONS

=over 2

 -d date in mm/dd/yyyy format
 -t time of day in 24-hr format
 -x displays eXtra debug messages

=back

=head1 SEE ALSO

=head1 AUTHORS

Authors of this man page:

 Peter D Phan (pdphan@users.sourceforge.net)

