=head1 NAME

 hpisensor -  This sample openhpi application displays sensor info for all resources with Sensor Capability

=head1 SYNOPSIS 

hpisensor [-t -r -x -e]

=head1 DESCRIPTION

hpisensor displays sensor info for all resources with Sensor Capability .

=head1 OPTIONS

=over 2

 -t = show Thresholds also
 -r = show Range values also
 -s = show EventState also
 -e entity path = limit to a single entity
 -x = show eXtra debug messages

=back

=head1 SEE ALSO

=head1 AUTHORS

Authors of this man page:

 Peter D Phan (pdphan@users.sourceforge.net)

