=head1 NAME

hpithres -  This sample openhpi application interactively displays sensors and sensor info. 

=head1 SYNOPSIS 

hpithres [-x]

=head1 DESCRIPTION

hpithres interactively displays sensor info for resources with Sensor Capability. Resources, sensors,and sensor info can be individually selected.

=head1 OPTIONS

=over 2

-x  Display debug messages

=back

=head1 SEE ALSO

=head1 AUTHORS

Authors of this man page:

 Peter D Phan (pdphan@users.sourceforge.net)

