=head1 NAME

hpitree - A openhpi sample application that shows in details the resources (rpt's)
and resources' manamegement instruments (rdr's) data structures of the managed openHPI complex. 

=head1 SYNOPSIS 

hpitree [ -a -c -d -i -o -r -s -w -n -x ]

=head1 DESCRIPTION

hpitree walks the Resource Presence Table (RPT) of the managed openHPI complex, and displays in details the resources (rpt's) and resources' management instruments (rdr's) data structures.

=head1 OPTIONS

=over 2

 (No Option) Display all rpts and rdrs
 -a     Display all rpts and rdrs
 -c     Display only controls
 -d     Display rdr records
 -i     Display only inventories
 -o     Display system overview: rpt & rdr headers
 -r     Display only rpts
 -s     Display only sensors
 -w     Display only watchdog
 -n     Select particular resource id to display
        (Used with [-cdirs] options)
 -x     Display debug messages

=back

=head1 SEE ALSO
  

=head1 AUTHORS

Authors of this man page:

 Peter D Phan (pdphan@users.sourceforge.net)

