=head1 NAME


hpitop - A openhpi sample application that displays highlevel topology for a managed openHPI complex.

=head1 SYNOPSIS 

hpitop [-r -s -c -w -i -a -x]

=head1 DESCRIPTION

hpitop walks the Resource Present Table (RPT) of the managed openHPI complex and displays all the resources and resources' management instruments. 

=head1 OPTIONS

=over 2

 (No Option) Display system topology: rpt & rdr headers
 -r     Display only rpts
 -s     Display only sensors
 -c     Display only controls
 -w     Display only watchdogs
 -i     Display only inventories
 -a     Display only annunciators
 -x     Display debug messages

=back

=head1 SEE ALSO
 

=head1 AUTHORS

Authors of this man page:

 Peter D Phan (pdphan@users.sourceforge.net)

