=head1 NAME

hpiwdt -  This sample openhpi application reads and enables the watchdog timer. 

=head1 SYNOPSIS 

hpiwdt [-derx -t sec]

=head1 DESCRIPTION

hpiwdt reads and enables the watchdog timer. 

=head1 OPTIONS

=over 2

 -e     enables the watchdog timer
 -d     disables the watchdog timer
 -r     resets the watchdog timer
 -t N   sets timeout to N seconds
 -x     show eXtra debug messages

=back

=head1 SEE ALSO

=head1 AUTHORS

Authors of this man page:

 Peter D Phan (pdphan@users.sourceforge.net)

