=head1 NAME

openhpi - an implementation of the SA Forum's Hardware Platform Interface

=head1 DESCRIPTION

OpenHPI is an implementation of the SA Forum's Hardware Platform
Interface, which provides a standard C library interface to manage,
monitor, and control hardware (both local and remote).

OpenHPI 2.x implements the HPI B.01.01 specification.

The OpenHPI client library (libopenhpi) provides all the connection
functionality needed by the client application to connect to the OpenHPI
daemon running on the local or remote server.

=head1 ENVIRONMENTAL VARIABLES

Some of OpenHPI's functioning can be changed by setting environment
variables.  This documents all client environmental settings.

=over 2

=item B<OPENHPI_DAEMON_HOST>=URL

URL for the host running the daemon. This can be "localhost" (default)
if the daemon is running on the local host or an ip address. 

=item B<OPENHPI_DAEMON_PORT>=PORT_NUMBER

The port number the host is listening on for clent connections.
Default port is 4743.

=back

=head1 HARDWARE SUPPORT

OpenHPI provides a number of plugins that talk to different hardware
types.  The following is a list of tested plugins in OpenHPI 2.x.

=over 4

=item B<ipmi>

An IPMI plugin that can talk locally (via smi interface and OpenIPMI
device driver) or remotely (via IPMI over LAN).  It supports IPMI 1.5
for standard rackmount servers, and some of IPMI 2.0 for support of
ATCA chassis.

IPMI plugin depends on libOpenIPMI version 1.4.x.

=item B<ipmidirect>

An IPMI plugin designed specifically for ATCA chassis.  It implements
IPMI commands directly in the plugin.

=item B<snmp_bc>

An SNMP based plugin that can communicate with IBM BladeCenter, as
well as IBM xSeries servers with RSA 1 adapters.

SNMP_BC plugin depends on net-snmp > 5.0.7.

=item B<sysfs>

Current status??

=item B<watchdog>

Current status??

=back

=head1 OTHER DOCUMENTATION

The definitive guide to HPI is the SA Forum specification at
http://saforum.org.

More info on OpenHPI can be found at our webpage
(http://openhpi.org).

=head1 SEE ALSO

The following man pages may also be of interest

=over 1

=item B<openhpid>

The openhpi daemon, providing OpenHPI data as a system service.

=back

=head1 AUTHORS

Authors of this man page:

 Sean Dague (http://dague.net/sean)
 Renier Morales (renier@openhpi.org)

