all:

install:
	@ln -f tpmtoken_setpasswd_tests.sh ../../../../bin/
	@ln -f tpmtoken_setpasswd_tests_exp01.sh ../../../../bin/
	@ln -f tpmtoken_setpasswd_tests_exp02.sh ../../../../bin/
	@ln -f tpmtoken_setpasswd_tests_exp03.sh ../../../../bin/
	@ln -f tpmtoken_setpasswd_tests_exp04.sh ../../../../bin/

clean:

