#	Copyright (c) Google LLC, 2018
#	SPDX-License-Identifier: GPL-2.0-or-later

top_srcdir ?= ../../../..

include $(top_srcdir)/include/mk/testcases.mk

CFLAGS = -pthread

include $(top_srcdir)/include/mk/generic_leaf_target.mk
