#!/bin/bash
# vi: set ts=8 sw=8 autoindent noexpandtab :
################################################################################
##									      ##
## (C) Copyright IBM Corp. 2003						      ##
##									      ##
## This program is free software;  you can redistribute it and#or modify      ##
## it under the terms of the GNU General Public License as published by       ##
## the Free Software Foundation; either version 2 of the License, or	      ##
## (at your option) any later version.					      ##
##									      ##
## This program is distributed in the hope that it will be useful, but	      ##
## WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY ##
## or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License   ##
## for more details.							      ##
##									      ##
## You should have received a copy of the GNU General Public License	      ##
## along with this program;  if not, write to the Free Software		      ##
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA    ##
##									      ##
################################################################################
#
# File :	warning
#
# Description:	Issue a warning message from the scenario file.
#
# Author:	Robert Paulsen, rpaulsen@us.ibm.com
#
# History:	Mar 18 2003 - Created. Robert Paulsen. rpaulsen@us.ibm.com

# establish PATH
cd `dirname $0`
LTPBIN=${PWD%%/testcases/*}/testcases/bin
PATH=$LTPBIN:$PATH

################################################################################
# main
################################################################################

#
# Input:
#
#	$1	TCNAME
#	$2+	message (rest of command line)

export TST_TOTAL=1
export TST_COUNT=1
export TCID=$1 ; shift
tst_resm TWARN	"$*"
