# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) Linux Test Project, 2026

top_srcdir		?= ../../..

include $(top_srcdir)/include/mk/env_pre.mk

INSTALL_TARGETS		:= *.sh

include $(top_srcdir)/include/mk/generic_leaf_target.mk
