# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2009, Cisco Systems Inc.
# Ngie Cooper, July 2009

top_srcdir			?= ../../../..

include $(top_srcdir)/include/mk/testcases.mk

CPPFLAGS			+= -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE

include $(top_srcdir)/include/mk/generic_leaf_target.mk
