# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2023 FUJITSU LIMITED. All rights reserved.
# Author: Yang Xu <xuyang2018.jy@fujitsu.com>

top_srcdir		?= ../../../..

include $(top_srcdir)/include/mk/testcases.mk

include $(top_srcdir)/include/mk/generic_leaf_target.mk
