# Not Linux, so don't expect a Linux tree.
--no-tree

-f --terse --no-summary

# enable more tests
--strict

# kernel specific
--ignore PREFER_KERNEL_TYPES,STRCPY,STRLCPY,STRNCPY

# TODO: document reason
--ignore CONST_STRUCT,VOLATILE,SPLIT_STRING,FILE_PATH_CHANGES,LONG_LINE,MACRO_ARG_REUSE,SPACING,MULTIPLE_ASSIGNMENTS,UNNECESSARY_PARENTHESES,PARENTHESIS_ALIGNMENT,CONCATENATED_STRING
