# Not Linux, so don't expect a Linux tree.
--no-tree

-f --terse --no-summary

# allow // in headers
--spdx-cxx-comments

# enable more tests
--strict

# kernel specific
--ignore PREFER_KERNEL_TYPES,STRCPY,STRLCPY,STRNCPY

# TODO: document reason
--ignore CONST_STRUCT,VOLATILE,FILE_PATH_CHANGES,LONG_LINE,MACRO_ARG_REUSE,MULTIPLE_ASSIGNMENTS

# ENOSYS is used in test error macros
--ignore ENOSYS
