# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) International Business Machines  Corp., 2001

top_srcdir		?= ../../../../..

include $(top_srcdir)/include/mk/env_pre.mk

LIB			:= libipc.a libmsgctl.a

include $(top_srcdir)/include/mk/lib.mk
