# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2015 Fujitsu Ltd.
# Author:Zhang Jin <jy_zhangjin@cn.fujitsu.com>

top_srcdir		?= ../../..

include $(top_srcdir)/include/mk/env_pre.mk

INSTALL_TARGETS		:= df01.sh

include $(top_srcdir)/include/mk/generic_leaf_target.mk
