#!/bin/bash
#
# Copyright 2000 by Hans Reiser, licensing governed by reiserfs/README
#
if [ $# -lt 2 ]
then
   echo
   echo "Usage : run_mogo <device> <processes>"
   echo
   echo "Example :"
   echo "# run_mogo /dev/hdx1 2"
   echo
   exit
fi

DEVICE=$1
NPROC=$2

y="Yes"
echo "WARNING : All data will be erased on device=$DEVICE "
echo "Run ? (Yes | no)"
read x

if [ -z $x ]
then
  exit
fi

if ! [ $x = $y ]
then
   exit
fi

./mongo.pl reiserfs $DEVICE /testfs reiserfs $NPROC
./mongo.pl ext2     $DEVICE /testfs ext2    $NPROC
./mongo_compare  ./results/ext2.tbl ./results/reiserfs.tbl ./results/html/ext2_vs_reiserfs
