#!/bin/sh

################################################################################
##                                                                            ##
## Copyright (c) International Business Machines  Corp., 2005                 ##
##                                                                            ##
## This program is free software;  you can redistribute it and#or modify      ##
## it under the terms of the GNU General Public License as published by       ##
## the Free Software Foundation; either version 2 of the License, or          ##
## (at your option) any later version.                                        ##
##                                                                            ##
## This program is distributed in the hope that it will be useful, but        ##
## WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY ##
## or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License   ##
## for more details.                                                          ##
##                                                                            ##
## You should have received a copy of the GNU General Public License          ##
## along with this program;  if not, write to the Free Software               ##
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA    ##
##                                                                            ##
##                                                                            ##
################################################################################
#
# File:
#   if4-alias-adddel
#
# Description:
#   Verify the IPv4 connectivity isn't broken with adding and deleting an
#   IPv4 alias many times
#    test01 - by `ifconfig add' style
#    test02 - by `ifconfig ethn:n' style
#    test03 - by ip command
#
# Setup:
#   See ltp-yyyymmdd/testcases/network/stress/README
#
# Author:
#   Mitsuru Chinen <mitch@jp.ibm.com>
#
# History:
#	Oct 19 2005 - Created (Mitsuru Chinen)
#
#-----------------------------------------------------------------------
# Uncomment line below for debug output.
#trace_logic=${trace_logic:-"set -x"}
$trace_logic

# Make sure the value of LTPROOT
LTPROOT=${LTPROOT:-`(cd ../../../../ ; pwd)`}
export LTPROOT

# Total number of the test case
TST_TOTAL=3
export TST_TOTAL

# Default of the test case ID and the test case count
TCID=if4-alias-adddel
TST_COUNT=0
export TCID
export TST_COUNT

# Check the environmanet variable
. check_envval || exit $TST_TOTAL

# The number of the add/delete IPv4 alias
NS_TIMES=${NS_TIMES:-10000}

# The interval of the check interface activity
CHECK_INTERVAL=${CHECK_INTERVAL:-`expr $NS_TIMES \/ 100`}

# The number of the test link where tests run
LINK_NUM=0

# Network portion of the IPv4 address
IPV4_NETWORK=${IPV4_NETWORK:-"10.0.0"}

# Netmask of for the tested network
IPV4_NETMASK="255.255.255.0"
IPV4_NETMASK_NUM=24

# Broadcast address of the tested network
IPV4_BROADCAST=${IPV4_NETWORK}.255

# Host portion of the IPv4 address of the remote host
RHOST_IPV4_HOST=${RHOST_IPV4_HOST:-"1"}

# Host portion of the non-alias
LHOST_IPV4_HOST=${LHOST_IPV4_HOST:-"254"}


#-----------------------------------------------------------------------
#
# NAME:
#   do_setup
#
# DESCRIPTION:
#   Make a IPv4 connectivity
#
# SET VALUES:
#   rhost_ipv4addr	- IPv4 Address of the remote host
#   lhost_ifname	- Interface name of the local host
#   rhost_ifname	- Interface name of the remote host
#
#-----------------------------------------------------------------------
do_setup()
{
    TCID=if4-alias-adddel
    TST_COUNT=0

    # Make sure the TCP traffic server/client doesn't run
    bg_tcp_traffic killall

    # Configure the interface at the remote host
    initialize_if rhost ${LINK_NUM}
    set_ipv4addr rhost ${LINK_NUM} ${IPV4_NETWORK} ${RHOST_IPV4_HOST}
    if [ $? -ne 0 ]; then
	tst_resm TBROK "Failed to initialize the interface at the remote host"
	exit $TST_TOTAL
    fi

    # IPv4 address of the remote host
    rhost_ipv4addr="${IPV4_NETWORK}.${RHOST_IPV4_HOST}"

    # Get the Interface name of local host
    lhost_ifname=`get_ifname lhost ${LINK_NUM}`
    if [ $? -ne 0 ]; then
	tst_resm TBROK "Failed to get the interface name at the local host"
	exit $TST_TOTAL
    fi

    # Get the Interface name of remote host
    rhost_ifname=`get_ifname rhost ${LINK_NUM}`
    if [ $? -ne 0 ]; then
	tst_resm TBROK "Failed to get the interface name at the remote host"
	exit $TST_TOTAL
    fi
}



#-----------------------------------------------------------------------
#
# NAME:
#   do_cleanup
#
# DESCRIPTION:
#   Recover the tested interfaces
#
#-----------------------------------------------------------------------
do_cleanup()
{
    # Make sure the TCP traffic server/client doesn't run
    bg_tcp_traffic killall

    # Initialize the interfaces
    initialize_if lhost ${LINK_NUM}
    initialize_if rhost ${LINK_NUM}
}



#-----------------------------------------------------------------------
#
# FUNCTION:
#   test_body
#
# DESCRIPTION:
#   main code of the test
#
# Arguments:
#   $1: define the test type
#	1 - `ifconfig add' style
#	2 - `ifconfig ethn:n' style
#	3 - ip command
#
#-----------------------------------------------------------------------
test_body()
{
    test_type=$1

    TCID=if4-alias-adddel0${test_type}
    TST_COUNT=$test_type

    case $test_type in
	1)	# Case of ifconfig add
	command_style="'ifconfig add'"
	;;
	2)	# Case of ifconfig ethn:n
	command_style="'ifconfig ethn:n'"
	;;
	3)	# Case of ip command
	command_style="ip command"
	;;
	*)
	tst_resm TBROK "unspecified case"
	return 1
	;;
    esac
    tst_resm TINFO "Verify the IPv4 connectivity is not broken when $command_style adds, then deletes an IPv4 alias $NS_TIMES times"

    # Make sure that no alias exists.
    initialize_if lhost ${LINK_NUM}
    if [ $? -ne 0 ]; then
	tst_resm TBROK "Failed to initialize the interface at the local host"
	return 1
    fi

    # Set the non-alias address
    set_ipv4addr lhost ${LINK_NUM} ${IPV4_NETWORK} ${LHOST_IPV4_HOST}
    if [ $? -ne 0 ]; then
	tst_resm TBROK "Failed to assign an IPv4 address to the interface at the local host"
	return 1
    fi
    lhost_ipv4addr="${IPV4_NETWORK}.${LHOST_IPV4_HOST}"

    # Check the connctivity
    ret=`$LTP_RSH $RHOST ${LTPROOT}/testcases/bin/check_icmpv4_connectivity $rhost_ifname $lhost_ipv4addr' ; echo $?'`
    if [ $ret -ne 0 ]; then
	tst_resm TBROK "Test Link $LINK_NUM is somthing wrong."
	return 1
    fi

    # IPv4 alias address of the localhost
    lhost_ipv4_alias_ip=${IPV4_NETWORK}.${test_type}${test_type}

    # The interface alias of local host
    case $test_type in
	1)	# Case of ifconfig add
	lhost_ifalias=${lhost_ifname}:0
	;;
	2)	# Case of ifconfig ethn:n
	lhost_ifalias=${lhost_ifname}:1
	;;
	# interface alias doesn't exist at ip command case.
    esac

    # Make a background TCP traffic from the non-alias address
    server_pid=`bg_tcp_traffic make $lhost_ipv4addr`

    # Start the loop
    cnt=0
    while [ $cnt -lt $NS_TIMES ]; do
	# Create
	case $test_type in
	    1)		# Case of ifconfig add
	    ifconfig $lhost_ifname add ${lhost_ipv4_alias_ip} netmask ${IPV4_NETMASK} broadcast ${IPV4_BROADCAST}
	    ;;
	    2)		# Case of ifconfig ethn:n
	    ifconfig $lhost_ifalias ${lhost_ipv4_alias_ip} netmask ${IPV4_NETMASK} broadcast ${IPV4_BROADCAST}
	    ;;
	    3)		# Case of ip command
	    ip addr add ${lhost_ipv4_alias_ip}/${IPV4_NETMASK_NUM} broadcast ${IPV4_BROADCAST} dev ${lhost_ifname}
	    ;;
	esac
	if [ $? -ne 0 ]; then
	    tst_resm TFAIL "Failed to add ${lhost_ipv4_alias_ip}".
	    return 1
	fi

	# Check the connectivity
	cnt=`expr $cnt + 1`
	if [ $CHECK_INTERVAL -ne 0 ]; then
	    if [ `expr $cnt % ${CHECK_INTERVAL}` -eq 0 ]; then
		if [ $test_type -ne 3 ]; then
		    # Case of ifconfig add / ifconfig ethn:n
		    check_icmpv4_connectivity $lhost_ifalias $rhost_ipv4addr
		else
		    # Case of ip command
		    check_icmpv4_connectivity $lhost_ifname $rhost_ipv4addr
		fi
		if [ $? -ne 0 ]; then
		    tst_resm TFAIL "$lhost_ifname is broken."
		    return 1
		fi
	    fi
	fi

	# Check the background TCP traffic
	bg_tcp_traffic check $server_pid
	if [ $? -ne 0 ]; then
	    server_pid=`bg_tcp_traffic make $lhost_ipv4addr`
	fi

	# Delete
	case $test_type in
	    1)		# Case of ifconfig add
	    ifconfig $lhost_ifalias del ${lhost_ipv4_alias_ip}
	    ;;
	    2)		# Case of ifconfig ethn:n
	    ifconfig ${lhost_ifalias} down
	    ;;
	    3)		# Case of ip command
	    ip addr del ${lhost_ipv4_alias_ip}/${IPV4_NETMASK_NUM} broadcast ${IPV4_BROADCAST} dev ${lhost_ifname}
	    ;;
	esac
	if [ $? -ne 0 ]; then
	    tst_resm TFAIL "Failed to delete ${lhost_ipv4_alias_ip}".
	    return 1
	fi
    done

    # Stop the background TCP traffic
    bg_tcp_traffic killall

    tst_resm TPASS "Test is finished correctly."
    return 0
}


#-----------------------------------------------------------------------
#
# Main
#
# Exit Value:
#   The number of the failure
#
#-----------------------------------------------------------------------

RC=0
do_setup
test_body 1 || RC=`expr $RC + 1`	# Case of ifconfig add
test_body 2 || RC=`expr $RC + 1`	# Case of ifconfig ethn:n
test_body 3 || RC=`expr $RC + 1`	# Case of ip command
do_cleanup

exit $RC
