#!/bin/sh
#set -x
cd $2
status=$(ps -ef|grep "testsf_s6"|wc -l)
if [ $status -le 2 ]
then
  exec 1< /dev/null       # open descriptor 1
  exec 2< /dev/null       # open descriptor 2
  nohup ./testsf_s6 $1 &
else
  echo "testsf_s6 $1 is already running on server, not restarting process"
fi
