# Copyright (c) 2018 - Linaro Limited. All rights reserved.
# SPDX-License-Identifier: GPL-2.0-or-later

top_srcdir		?= ../../../..

include $(top_srcdir)/include/mk/testcases.mk

include $(top_srcdir)/include/mk/generic_leaf_target.mk
