# SPDX-License-Identifier: GPL-2.0-or-later
#  Copyright (c) Wipro Technologies Ltd, 2002.  All Rights Reserved.
#  Copyright (C) International Business Machines  Corp., 2007
#
# HISTORY:
#  6/8/07 krisw@us.ibm.com  Copied change made in RHEL Makefile for seg fault.
#
#############################################################################

top_srcdir		?= ../../../..

include $(top_srcdir)/include/mk/testcases.mk

CFLAGS			+= -D_GNU_SOURCE

include $(top_srcdir)/include/mk/generic_leaf_target.mk
