# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2005-2014 Linux Test Project

top_srcdir		?= ../../../..

include $(top_srcdir)/include/mk/testcases.mk

MAKE_TARGETS		:=
INSTALL_TARGETS		:= isofs.sh

include $(top_srcdir)/include/mk/generic_leaf_target.mk
