SUBDIRS ?= fs-metadata page-poisoning

all:
	@for i in ${SUBDIRS}; do        \
		${MAKE} -C $$i $@;      \
	done

install:
	@for i in ${SUBDIRS}; do        \
		${MAKE} -C $$i $@;      \
	done

clean:
	@for i in ${SUBDIRS}; do        \
		${MAKE} -C $$i $@;      \
	done
