#!/bin/sh
#*********************************************************************
#   Copyright (c) International Business Machines  Corp., 2000
#
#   This program is free software;  you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY;  without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
#   the GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program;  if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
#
#  FILE   : cron
#
#  PUROPOSE: Ensure that the following directories only have root write access
#			/etc/cron.d
#			/etc/cron.daily
#			/etc/cron.hourly
#			/etc/cron.monthly
#			/etc/cron.weekly
#			/var/spool/cron
#	HISTORY:
#		Jerone Young (jyoung5@us.ibm.com)
#

DIRS="/etc/cron.d /etc/cron.daily /etc/cron.hourly /etc/cron.monthly /etc/cron.weekly /var/spool/cron"

EXIT_CODE=0
for i in $DIRS
do
	cron_dirs_check $i
	if [ $? != 0 ]
	then
		echo "$i FAILED TEST!!!!!"
		EXIT_CODE=1
	fi

done

exit $EXIT_CODE
