#
# Softdog v1.21
# (C) Christophe Dupre 1998

CC	= gcc
BINNAME	= softdog
MANNAME	= softdog.8
STRIP   = strip
#INCLUDE	= 
OPTIMIZE	= -O2 -fomit-frame-pointer -fno-strength-reduce
#DEBUG	= -g -DDEBUG
CFLAGS	= -Wall $(DEBUG) $(INCLUDE) $(OPTIMIZE)\
          -DDEVICE=\"$(DEVICE)\" -DMY_MAJOR=$(MAJOR) -DMY_MINOR=$(MINOR)\
          -DBINNAME=\"$(BINNAME)\"

# Installation paths
PREFIX	=
BINDIR	=$(PREFIX)/sbin
MANDIR	=/usr/man/man8

# Install program and options
TARGETS	=softdog installbin installman installdev
INSTALL	=install 
BININSTALLOPTS	= -m0555
MANINSTALLOPTS	= -m0644
#INSTALL = cp

# mknod program
MKNOD	=mknod 

# Watchdog device info
DEVICE	=$(PREFIX)/dev/watchdog
MAJOR	=10
MINOR	=130
TYPE	=c

all: softdog

softdog: softdog.o
	$(CC) $(CFLAGS) -o $(BINNAME) $<
	$(STRIP) $(BINNAME)

install: $(TARGETS)
installbin:
	mkdir -p $(BINDIR)
	$(INSTALL) $(BININSTALLOPTS) $(BINNAME) $(BINDIR)/$(BINNAME)
installman:
	mkdir -p $(MANDIR)
	$(INSTALL) $(MANINSATALLOPTS) $(MANNAME) $(MANDIR)/$(MANNAME)
	gzip -9 $(MANDIR)/$(MANNAME)
installdev:
	rm -f $(DEVICE)
	$(MKNOD) $(DEVICE) $(TYPE) $(MAJOR) $(MINOR)
	
clean:
	rm -f *.[oas] *~ core $(BINNAME) 
