# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (c) 2019 FUJITSU LIMITED. All rights reserved.
# Author: Xiao Yang <yangx.jy@cn.fujitsu.com>

top_srcdir              ?= ../../../..

include $(top_srcdir)/include/mk/env_pre.mk

INSTALL_TARGETS         := binfmt_misc01.sh binfmt_misc_lib.sh

include $(top_srcdir)/include/mk/generic_leaf_target.mk
