# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) Linux Test Project, 2021

top_srcdir	?= ../../../../../../..

include	$(top_srcdir)/include/mk/env_pre.mk

INSTALL_DIR		:= testcases/data/ima_selinux
INSTALL_TARGETS	:= *.policy

include $(top_srcdir)/include/mk/generic_leaf_target.mk
