# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2026 Cyril Hrubis <chrubis@suse.cz>

top_srcdir		?= ../../..

include $(top_srcdir)/include/mk/env_pre.mk
include $(top_srcdir)/include/mk/generic_trunk_target.mk
