#!/bin/bash

function runtest() {

	$IPMITOOL $*
	RETURN=$?
	if [ $RETURN -ne 0 ]; then
		echo "Test ipmitool $* failed with code $RETURN."
		status=$(($status+1))
	fi
}

CHECK=`dmidecode | egrep '(Baseboard Management Controller|IPMI)'` 
if [ -z "$CHECK" ]; then
	echo "BMC is not detected. Aborting."
	exit 255
fi

IPMITOOL=`ls $POUNDER_OPTDIR/ipmitool*/src/ipmitool 2> /dev/null`
if [ -z "$IPMITOOL" ]; then
	IPMITOOL=`which ipmitool 2> /dev/null`
	if [ -z "$IPMITOOL" ]; then
		echo "Cannot find ipmitool; did you run Install?"
		exit -1
	fi
else
	IPMITOOL="$POUNDER_OPTDIR/ipmitool*/src/ipmitool"
fi

status=0
/etc/init.d/ipmi restart #maybe start
RETURN=$?
if [ $RETURN -ne 0 ]; then
	echo "Could not start driver with code $RETURN."
	status=$(($status+1))
	exit $status
fi

runtest bmc info
if [ $status -eq 0 ]; then
	BMC2=`$IPMITOOL bmc info | grep "IPMI Version" | cut -b 29`
	#possibly log this stuff here
	if [ $BMC2 -ge 2 ]; then
		runtest firewall info lun 0 netfn 0
		runtest firewall info
		runtest firewall disable lun 0 netfn 0 cmd 2
		runtest firewall info lun 0 netfn 0
		runtest firewall enable lun 0 netfn 0 cmd 2
		#runtest firewall reset
		runtest channel getciphers 1
	else
		echo "BMC is not 2.0 compatible; skipping firewall tests."	
	fi
fi
runtest bmc getenables
runtest channel authcap 1 1
runtest channel authcap 1 2
runtest channel authcap 1 3
runtest channel authcap 1 4
runtest channel authcap 1 5
runtest chassis status
runtest chassis poh
runtest chassis restart_cause
runtest chassis power status
runtest fru print
runtest pef info
runtest pef status
runtest pef policy
runtest pef list
runtest sdr info
runtest sdr list all
runtest sel info
runtest sel list
runtest sel list 5
runtest sel time get
runtest sel writeraw testing
runtest sel readraw testing
runtest sensor list
runtest session info all
runtest sol info
runtest user summary
runtest user list


if [ $status -eq 255 ]; then
	status=254
fi



exit $status
