#!/bin/sh

CONFIGAGENT createUser initial MD5 initial_test_pass_auth DES initial_test_pass_priv
CONFIGAGENT createUser templateMD5 MD5 templateMD5_test_pass_auth DES templateMD5_test_pass_priv
CONFIGAGENT rwuser initial
CONFIGAGENT rwuser newtestuser
