#!/bin/sh

. ../eval_tools.sh

HEADER SNMPv1 support

#
# Begin test
#

# standard V1 configuration: testcomunnity
. ./Sv1config

STARTAGENT

CAPTURE "snmpget -On $SNMP_FLAGS -c testcommunity -v 1 udp:localhost:$SNMP_SNMPD_PORT .1.3.6.1.2.1.1.3.0"

CHECKORDIE ".1.3.6.1.2.1.1.3.0 = Timeticks:"

CAPTURE "snmpgetnext -On $SNMP_FLAGS -c testcommunity -v 1 udp:localhost:$SNMP_SNMPD_PORT .1.3.6.1.2.1.1.3"

CHECKORDIE ".1.3.6.1.2.1.1.3.0 = Timeticks:"

CAPTURE "snmpget -On $SNMP_FLAGS -c testcommunity -v 1 udp:localhost:$SNMP_SNMPD_PORT .1.3.6.1.2.1.1.3.1"

CHECKORDIE "Error in packet"

CAPTURE "snmpget -On $SNMP_FLAGS -c notavalidcommunity -v 1 udp:localhost:$SNMP_SNMPD_PORT .1.3.6.1.2.1.1.3.0"

CHECKORDIE "Timeout"

STOPAGENT

FINISHED
