#!/bin/sh

#
# test snmpv2c get support by reading a variable
#

. ../eval_tools.sh

HEADER for failure of SNMPv2c get against SNMPv1 agent

#
# Begin test
#

# standard V2C configuration: testcomunnity
. ./Sv1config

STARTAGENT

CAPTURE "snmpget -On $SNMP_FLAGS -c notavalidcommunity -v 2c udp:localhost:$SNMP_SNMPD_PORT .1.3.6.1.2.1.1.3.0"

STOPAGENT

CHECK "Timeout"

FINISHED
