#!/bin/sh

. ../eval_tools.sh

HEADER for failure of SNMPv1 get against SNMPv2c agent

#
# Begin test
#

# standard V2C configuration: testcomunnity
. ./Sv2cconfig

STARTAGENT

CAPTURE "snmpget -On $SNMP_FLAGS -c notavalidcommunity -v 1 udp:localhost:$SNMP_SNMPD_PORT .1.3.6.1.2.1.1.3.0"

STOPAGENT

CHECK "Timeout"

FINISHED
