#!/bin/sh

. ../eval_tools.sh

HEADER SNMPv3 get using templateSHA/SHA of .1.3.6.1.2.1.1.3.0

SKIPIFNOT USE_OPENSSL

#
# Begin test
#

# standard V3 configuration for templateSHA user
. ./Sv3configsha

STARTAGENT

CAPTURE "snmpget -On $SNMP_FLAGS -v 3 -a SHA -A initial_test_pass_auth -l anp -u initial udp:localhost:$SNMP_SNMPD_PORT .1.3.6.1.2.1.1.3.0"

STOPAGENT

CHECK ".1.3.6.1.2.1.1.3.0 = Timeticks:"

FINISHED
