# SPDX-License-Identifier: GPL-2.0-or-later
#  Copyright (C) 2015 Cedric Hnyda ced.hnyda@gmail.com

top_srcdir		?= ../../../..

include $(top_srcdir)/include/mk/testcases.mk

include $(top_srcdir)/include/mk/generic_leaf_target.mk
