# SPDX-License-Identifier: GPL-2.0-or-later

top_srcdir		:= ../../..

include $(top_srcdir)/include/mk/testcases.mk

CPPFLAGS		+= -D_GNU_SOURCE

LDLIBS			+= -pthread


include $(top_srcdir)/include/mk/generic_leaf_target.mk
