# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) Cyril Hrubis <chrubis@suse.cz>

top_srcdir		?= ../..

include $(top_srcdir)/include/mk/env_pre.mk

INTERNAL_LIB		:= libujson.a

include $(top_srcdir)/include/mk/lib.mk
include $(top_srcdir)/include/mk/generic_leaf_target.mk
