# SPDX-License-Identifier: GPL-2.0-or-later
#  Copyright (c) International Business Machines  Corp., 2008

top_srcdir		?= ../../../..

include $(top_srcdir)/include/mk/testcases.mk

CFLAGS			+= -pthread

include $(top_srcdir)/include/mk/generic_leaf_target.mk
