#!/bin/sh
# Copyright (c) 2015 Oracle and/or its affiliates. All Rights Reserved.
# Copyright (c) International Business Machines  Corp., 2003
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#  PURPOSE: Creates a text file of specified size locally and copies
#           the file to an NFS mountpoint.  The two files are compared
#           and checked for differences.  If the files differ, then
#           the test fails.  By default, this test creates a 10Mb file
#           and runs for one loop.
#
# Created by: Robbie Williamson (robbiew@us.ibm.com)

TCID="nfs04"
TST_TOTAL=1
TST_CLEANUP="nfs_cleanup"

. nfs_lib.sh
. test_net.sh

nfs_setup

tst_resm TINFO "create 10M file"
ROD nfs04_create_file 10 nfs04.testfile
tst_resm TPASS "Test finished"

tst_exit
