
###########################################################################
# name of file  : Makefile                                                #
# description   : make(1) description file for                            #
###########################################################################

# all executables in this directory are considered testcases
TARGETS=`find . -maxdepth 1 -perm +111 -type f`
all:
	#$(MAKE) -C uClibctest

install:
	#for i in $(TARGETS) ; do cp -f $$i ../../bin || break ; done
	#$(MAKE) -C uClibctest install

uninstall:
	#for j in $(TARGETS) ; do rm -f ../../bin/$$j ; done
	#$(MAKE) -C uClibctest uninstall

clean:
	#@rm -f *~
	#$(MAKE) -C uClibctest clean

