# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) SUSE 2015

top_srcdir			?= ../../..

LTPLIBS = uinput

include $(top_srcdir)/include/mk/testcases.mk

LDLIBS += -lltpuinput

include $(top_srcdir)/include/mk/generic_leaf_target.mk
