# SPDX-License-Identifier: GPL-2.0-or-later
#  Copyright (c) Linux Test Project, 2017

top_srcdir		?= ../../../..

include $(top_srcdir)/include/mk/testcases.mk

include $(top_srcdir)/include/mk/generic_leaf_target.mk
