# SPDX-License-Identifier: GPL-2.0-or-later
#  Copyright (c) Red Hat Inc., 2011

top_srcdir		?= ../../../..

include $(top_srcdir)/include/mk/testcases.mk

include $(top_srcdir)/include/mk/generic_leaf_target.mk
