# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2016 Fujitsu Ltd.
# Author:Xiao Yang <yangx.jy@cn.fujitsu.com>

top_srcdir		?= ../../..

include $(top_srcdir)/include/mk/env_pre.mk

INSTALL_TARGETS		:= wc01.sh

include $(top_srcdir)/include/mk/generic_leaf_target.mk
