#!/bin/sh
#
# Copyright (c) 2001 Silicon Graphics, Inc.  All Rights Reserved.
# Copyright (c) International Business Machines  Corp., 2001
#
# This program is free software;  you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY;  without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
# the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program;  if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
#
#
#
# Proper error checking and result reporting still needed
#
# usage:  fsxtest02 $1
# $1 number of operations to perform

#Uncomment line below for debugging
#set -x

TCbin=${TCbin:-`pwd`}
TCtmp=${TCtmp:-/tmp/fsxtest2.$$}

mkdir -p $TCtmp 2>/dev/null
touch $TCtmp/testfile
$TCbin/fsx-linux -N $1 $TCtmp/testfile
RESULT=$?
# report the results
if [ $RESULT -eq "0" ]; then
  echo "PASS: fsxtest02 $1 $2 $3"
else
  echo "FAIL: fsxtest02 $1 $2 $3"
fi
rm -rf $TCtmp
exit $RESULT
