#!/bin/bash

# Build CPU frequency switching test program

# Copyright (C) 2003-2006 IBM
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
# 02111-1307, USA.


# Do any CPU support cpufreq?
CPUFREQ_ENABLED_CPUS=`/bin/ls -lad /sys/devices/system/cpu/cpu*/cpufreq 2> /dev/null | wc -l`
if [ "$CPUFREQ_ENABLED_CPUS" -lt 1 ]; then
        echo "[cpufreq] None of your CPUs support cpufreq. Not building cpufreq."
        exit 255
fi

cd "$POUNDER_SRCDIR/cpufreq/"

make $*
exit $?
