#!/bin/bash

# Build the program that wiggles X windows.

# Copyright (C) 2003-2006 IBM
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
# 02111-1307, USA.

cd "$POUNDER_SRCDIR/xbonkers/"

make $*
RESULT=$?

if [ $RESULT -ne 0 ]; then
        echo
        echo "[xterm_stress] build failed; you probably need X11 devel packages."
        exit 1
fi

# Build a program to generate random coordinates for X11
# programs' -geometry flag.

cd "$POUNDER_SRCDIR/randacoords/"

make $*

