all:

install:
	@ln -f tpmtoken_init_tests.sh ../../../../bin/
	@ln -f tpmtoken_init_tests_exp00.sh ../../../../bin/
	@ln -f tpmtoken_init_tests_exp01.sh ../../../../bin/
	@ln -f tpmtoken_init_tests_exp02.sh ../../../../bin/
	@ln -f tpmtoken_init_tests_exp03.sh ../../../../bin/

clean:

