#!/bin/sh

TMP_FILE=${TMP:-/tmp}/cpu_$$
TM_DLY=1    # Time delay before start of entire new cycle.


CNT=0
while :
do

	: $(( CNT += 1 ))
	echo "Loop Count $CNT"

	echo 1 > $TMP_FILE
	# TODO:  Verify writes are complete and correct

	sleep $TM_DLY

done
