/*
   b_float.h   Generated by the Ballista(tm) Project data object compiler
   Copyright (C) 1998-2001  Carnegie Mellon University

   This program is free software; you can redistribute it and/or
   modify it under the terms of the GNU General Public License
   as published by the Free Software Foundation; either version 2
   of the License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

   File generated Friday, December 17 at 06:03 PM CST

TITLE
   b_float.h
*/

//include control
#ifndef B_FLOAT_H
#define B_FLOAT_H
#include <errno.h>
#include <iostream.h>
#include <stdio.h>
#include <stdlib.h>
#include <stream.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include "bTypes.h"

 #include "values.h" 
 #include "bTypes.h"
 #include <math.h>
 #define intBase unsigned short
 #define CLASSTYPE float
#define CLASSNAME b_float
#define CLASS_STRING "b_float"
#define CLASSPARENT paramAccess
#define NUMBER_OF_DIALS 1


class CLASSNAME:public CLASSPARENT
{
private:
  //CLASS DIAL SETTING STRING VARIABLES
  b_param _b_floatTYPENAME;
b_param _b_floatZERO;
int b_float_zero;
b_param _b_floatONE;
int b_float_one;
b_param _b_floatNEGONE;
int b_float_negone;
b_param _b_floatFMINEXP;
int b_float_fminexp;
b_param _b_floatMLN2;
int b_float_mln2;
b_param _b_floatMPI;
int b_float_mpi;
b_param _b_floatHALF_PI;
int b_float_half_pi;
b_param _b_floatQUARTER_PI;
int b_float_quarter_pi;
b_param _b_floatTWO_PI;
int b_float_two_pi;
b_param _b_floatMSQRT2;
int b_float_msqrt2;
b_param _b_floatE;
int b_float_e;
b_param _b_floatMAXFLOAT;
int b_float_maxfloat;
b_param _b_floatMINFLOAT;
int b_float_minfloat;
b_param _b_floatNEGMAXFLOAT;
int b_float_negmaxfloat;
b_param _b_floatNEGMINFLOAT;
int b_float_negminfloat;
  //TYPE VARIABLE TO SAVE VALUE FOR DESTRUCTION
  CLASSTYPE _theVariable;

 public:
  //CLASS DIAL SETTING STRING ACCESS METHODS
b_param *b_floatZERO();
b_param *b_floatONE();
b_param *b_floatNEGONE();
b_param *b_floatFMINEXP();
b_param *b_floatMLN2();
b_param *b_floatMPI();
b_param *b_floatHALF_PI();
b_param *b_floatQUARTER_PI();
b_param *b_floatTWO_PI();
b_param *b_floatMSQRT2();
b_param *b_floatE();
b_param *b_floatMAXFLOAT();
b_param *b_floatMINFLOAT();
b_param *b_floatNEGMAXFLOAT();
b_param *b_floatNEGMINFLOAT();
  //CLASS CONSTRUCTOR
  CLASSNAME();

public:
  //Mandatory Methods
  b_param *typeName();           //returns the type of parameter
  virtual void *access(b_param data[]);
  virtual int commit(b_param tname);
  virtual int cleanup(b_param tname);
  
  virtual int numDials(b_param tname);
  virtual int numItems(b_param tname,int dialNumber);
  virtual b_param *paramName(b_param tname,int dialNumber, int position);

  virtual int distanceFromBase();
  virtual void typeList(b_param list[],int num);
  
};



#endif      //CLASSNAME_H
