/*
   b_map_flag.cpp   Generated by the Ballista(tm) Project data object compiler
   Copyright (C) 1998-2001  Carnegie Mellon University

   This program is free software; you can redistribute it and/or
   modify it under the terms of the GNU General Public License
   as published by the Free Software Foundation; either version 2
   of the License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

   File generated Friday, December 17 at 06:07 PM CST

TITLE
   b_map_flag.cpp
*/

//--------------------------------------------------------------------

#include <errno.h>
#include <iostream.h>
#include <stdio.h>
#include <stdlib.h>
#include <stream.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>

#include "b_map_flag.h"

//--------------------------------------------------------------------


//--------------------------------------------------------------------

CLASSNAME::CLASSNAME()
{
  //DIAL DECLARATIONS HERE

  //generated

   strcpy(_b_map_flagTYPENAME,CLASS_STRING);
strcpy(_b_map_flagSHARED,"b_map_flag_SHARED");
strcpy(_b_map_flagPRIVATE,"b_map_flag_PRIVATE");
strcpy(_b_map_flagFIXED,"b_map_flag_FIXED");
strcpy(_b_map_flagALL,"b_map_flag_ALL");
}

//--------------------------------------------------------------------
b_param *b_map_flag::b_map_flagSHARED()
{
   return &_b_map_flagSHARED;
}

b_param *b_map_flag::b_map_flagPRIVATE()
{
   return &_b_map_flagPRIVATE;
}

b_param *b_map_flag::b_map_flagFIXED()
{
   return &_b_map_flagFIXED;
}

b_param *b_map_flag::b_map_flagALL()
{
   return &_b_map_flagALL;
}

//--------------------------------------------------------------------
//---------------------------------------------------------------------------
//type name return method

b_param *CLASSNAME::typeName()
{
  return &_b_map_flagTYPENAME;
}

//---------------------------------------------------------------------------
//---------------------------------------------------------------------------
int CLASSNAME::distanceFromBase()
{
  return CLASSPARENT::distanceFromBase() +1;
}


//---------------------------------------------------------------------------
void CLASSNAME::typeList(b_param list[], int num)
{
  strcpy(list[num],(char *) typeName());
  CLASSPARENT::typeList(list,num+1);
}
//--------------------------------------------------------------------
  void *CLASSNAME::access(b_param data[])
{
  if (strcmp(data[0],(char *)typeName())!=0)
    return CLASSPARENT::access(data);

  //ACCESS CODE
b_map_flag_shared = 0;
b_map_flag_private = 0;
b_map_flag_fixed = 0;
b_map_flag_all = 0;
   int dataPTR =0;


   dataPTR++;
if (strcmp(data[dataPTR],_b_map_flagSHARED)==0)
      b_map_flag_shared = 1;
   else if (strcmp(data[dataPTR],_b_map_flagPRIVATE)==0)
      b_map_flag_private = 1;
   else if (strcmp(data[dataPTR],_b_map_flagFIXED)==0)
      b_map_flag_fixed = 1;
   else if (strcmp(data[dataPTR],_b_map_flagALL)==0)
      b_map_flag_all = 1;
  else
    {
      cerr<<"Error: Unknown setting for the "
          <<"MAP_FLAG"
          <<" dial of the data object "
          <<CLASS_STRING
          <<". "<<endl
          <<"The offending string is : "
          <<data[dataPTR]
          <<endl;
      exit(1);
    }

 _theVariable = 0;

if (b_map_flag_shared==1 || b_map_flag_all==1)
{

 _theVariable |= MAP_SHARED;
 
}

if (b_map_flag_private==1 || b_map_flag_all==1)
{

 _theVariable |= MAP_PRIVATE;
 
}

if (b_map_flag_fixed==1 || b_map_flag_all==1)
{

 _theVariable |= MAP_FIXED;
 
}
   return &_theVariable;
}

//--------------------------------------------------------------------
  int CLASSNAME::commit(b_param tname)
{
  if (strcmp(tname,(char *)typeName())!=0)
    return CLASSPARENT::commit(tname);
  //COMMIT CODE HERE
//generated
   return 0;
}

//--------------------------------------------------------------------
  int CLASSNAME::cleanup(b_param tname)
{
  if (strcmp(tname,(char *)typeName())!=0)
    return CLASSPARENT::cleanup(tname);
      
  //CLEANUP CODE
//generated
   return 0;
}

//--------------------------------------------------------------------
int CLASSNAME::numDials(b_param tname)
{
  if (!strcmp(tname,(char *)typeName()))
    return NUMBER_OF_DIALS;
  else return CLASSPARENT::numDials(tname);
      
}


//---------------------------------------------------------------------------
int CLASSNAME::numItems(b_param tname,int dialNumber)
{
  if (strcmp(tname,(char *)typeName())!=0)
    return CLASSPARENT::numItems(tname,dialNumber);
  switch (dialNumber)
    {
      //NUMITEMS SWITCH CASES HERE
      //generated

   case 1:
      return 4;
      break;
//---------------------------------------------------------------------------
      //end generated

    default:
      cerr<<"Error, invalid dial number passed to "
          <<CLASS_STRING<<"::numItems\n"
          <<"Please check declaration files.  Dial number passed was "
          <<dialNumber<<endl;
      exit(1);
    }
  return 0;
}

//---------------------------------------------------------------------------
b_param *CLASSNAME::paramName(b_param tname,
                                   int dialNumber,
                                   int position)

{
  if (strcmp(tname,(char *)typeName())!=0)
    return CLASSPARENT::paramName(tname,dialNumber,position);
  
  switch (dialNumber)
    {
      //PARAMNAME SWITCH CASES HERE
      //generated

case 1:
 switch (position)
   {
      case 1:
         return b_map_flagSHARED();
         break;
      case 2:
         return b_map_flagPRIVATE();
         break;
      case 3:
         return b_map_flagFIXED();
         break;
      case 4:
         return b_map_flagALL();
         break;

      default:
          cerr<<"Error, invalid position number passed to "
              <<CLASS_STRING<<"::paramName\n"
              <<"Please check declaration files.  Dial number passed was"
              <<dialNumber<<" position "<<position<<".\n";
          exit(1);
   }
   break;
    default:
      cerr<<"Error, invalid dial number passed to "
          <<CLASS_STRING<<"::paramName\n"
          <<"Please check declaration files.  Dial number passed was "
          <<dialNumber<<endl;
      exit(1);

    }
  return NULL;
}

//---------------------------------------------------------------------------
