/*
   b_pid.cpp   Generated by the Ballista(tm) Project data object compiler
   Copyright (C) 1998-2001  Carnegie Mellon University

   This program is free software; you can redistribute it and/or
   modify it under the terms of the GNU General Public License
   as published by the Free Software Foundation; either version 2
   of the License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

   File generated Friday, December 17 at 06:08 PM CST

TITLE
   b_pid.cpp
*/

//--------------------------------------------------------------------

#include <errno.h>
#include <iostream.h>
#include <stdio.h>
#include <stdlib.h>
#include <stream.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>

#include "b_pid.h"

//--------------------------------------------------------------------


//--------------------------------------------------------------------

CLASSNAME::CLASSNAME()
{
  //DIAL DECLARATIONS HERE

  //generated

   strcpy(_b_pidTYPENAME,CLASS_STRING);
strcpy(_b_pidPID_SELF,"b_pid_PID_SELF");
strcpy(_b_pidPID_CHILD,"b_pid_PID_CHILD");
strcpy(_b_pidPID_65535,"b_pid_PID_65535");
strcpy(_b_pidPID_65536,"b_pid_PID_65536");
}

//--------------------------------------------------------------------
b_param *b_pid::b_pidPID_SELF()
{
   return &_b_pidPID_SELF;
}

b_param *b_pid::b_pidPID_CHILD()
{
   return &_b_pidPID_CHILD;
}

b_param *b_pid::b_pidPID_65535()
{
   return &_b_pidPID_65535;
}

b_param *b_pid::b_pidPID_65536()
{
   return &_b_pidPID_65536;
}

//--------------------------------------------------------------------
//---------------------------------------------------------------------------
//type name return method

b_param *CLASSNAME::typeName()
{
  return &_b_pidTYPENAME;
}

//---------------------------------------------------------------------------
//---------------------------------------------------------------------------
int CLASSNAME::distanceFromBase()
{
  return CLASSPARENT::distanceFromBase() +1;
}


//---------------------------------------------------------------------------
void CLASSNAME::typeList(b_param list[], int num)
{
  strcpy(list[num],(char *) typeName());
  CLASSPARENT::typeList(list,num+1);
}
//--------------------------------------------------------------------
  void *CLASSNAME::access(b_param data[])
{
  if (strcmp(data[0],(char *)typeName())!=0)
    return CLASSPARENT::access(data);

  //ACCESS CODE
b_pid_pid_self = 0;
b_pid_pid_child = 0;
b_pid_pid_65535 = 0;
b_pid_pid_65536 = 0;
   int dataPTR =0;


   dataPTR++;
if (strcmp(data[dataPTR],_b_pidPID_SELF)==0)
      b_pid_pid_self = 1;
   else if (strcmp(data[dataPTR],_b_pidPID_CHILD)==0)
      b_pid_pid_child = 1;
   else if (strcmp(data[dataPTR],_b_pidPID_65535)==0)
      b_pid_pid_65535 = 1;
   else if (strcmp(data[dataPTR],_b_pidPID_65536)==0)
      b_pid_pid_65536 = 1;
  else
    {
      cerr<<"Error: Unknown setting for the "
          <<"PID"
          <<" dial of the data object "
          <<CLASS_STRING
          <<". "<<endl
          <<"The offending string is : "
          <<data[dataPTR]
          <<endl;
      exit(1);
    }

if (b_pid_pid_self==1)
{

 _theVariable = getpid();
 
}

if (b_pid_pid_child==1)
{

 static int pid_kid;
 if((pid_kid = fork())==0) /* many syscalls taking a pid need a child to exist */
 {
 sleep (1); 
 exit(0); 
 }
 _theVariable = pid_kid;
 
}

if (b_pid_pid_65535==1)
{

 _theVariable = 65535;
 
}

if (b_pid_pid_65536==1)
{

 _theVariable = 65536;
 
}
   return &_theVariable;
}

//--------------------------------------------------------------------
  int CLASSNAME::commit(b_param tname)
{
  if (strcmp(tname,(char *)typeName())!=0)
    return CLASSPARENT::commit(tname);
  //COMMIT CODE HERE
//generated
   return 0;
}

//--------------------------------------------------------------------
  int CLASSNAME::cleanup(b_param tname)
{
  if (strcmp(tname,(char *)typeName())!=0)
    return CLASSPARENT::cleanup(tname);
      
  //CLEANUP CODE
//generated
   return 0;
}

//--------------------------------------------------------------------
int CLASSNAME::numDials(b_param tname)
{
  if (!strcmp(tname,(char *)typeName()))
    return NUMBER_OF_DIALS;
  else return CLASSPARENT::numDials(tname);
      
}


//---------------------------------------------------------------------------
int CLASSNAME::numItems(b_param tname,int dialNumber)
{
  if (strcmp(tname,(char *)typeName())!=0)
    return CLASSPARENT::numItems(tname,dialNumber);
  switch (dialNumber)
    {
      //NUMITEMS SWITCH CASES HERE
      //generated

   case 1:
      return 4;
      break;
//---------------------------------------------------------------------------
      //end generated

    default:
      cerr<<"Error, invalid dial number passed to "
          <<CLASS_STRING<<"::numItems\n"
          <<"Please check declaration files.  Dial number passed was "
          <<dialNumber<<endl;
      exit(1);
    }
  return 0;
}

//---------------------------------------------------------------------------
b_param *CLASSNAME::paramName(b_param tname,
                                   int dialNumber,
                                   int position)

{
  if (strcmp(tname,(char *)typeName())!=0)
    return CLASSPARENT::paramName(tname,dialNumber,position);
  
  switch (dialNumber)
    {
      //PARAMNAME SWITCH CASES HERE
      //generated

case 1:
 switch (position)
   {
      case 1:
         return b_pidPID_SELF();
         break;
      case 2:
         return b_pidPID_CHILD();
         break;
      case 3:
         return b_pidPID_65535();
         break;
      case 4:
         return b_pidPID_65536();
         break;

      default:
          cerr<<"Error, invalid position number passed to "
              <<CLASS_STRING<<"::paramName\n"
              <<"Please check declaration files.  Dial number passed was"
              <<dialNumber<<" position "<<position<<".\n";
          exit(1);
   }
   break;
    default:
      cerr<<"Error, invalid dial number passed to "
          <<CLASS_STRING<<"::paramName\n"
          <<"Please check declaration files.  Dial number passed was "
          <<dialNumber<<endl;
      exit(1);

    }
  return NULL;
}

//---------------------------------------------------------------------------
