/*
   b_prot_flag.cpp   Generated by the Ballista(tm) Project data object compiler
   Copyright (C) 1998-2001  Carnegie Mellon University

   This program is free software; you can redistribute it and/or
   modify it under the terms of the GNU General Public License
   as published by the Free Software Foundation; either version 2
   of the License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

   File generated Friday, December 17 at 06:07 PM CST

TITLE
   b_prot_flag.cpp
*/

//--------------------------------------------------------------------

#include <errno.h>
#include <iostream.h>
#include <stdio.h>
#include <stdlib.h>
#include <stream.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>

#include "b_prot_flag.h"

//--------------------------------------------------------------------


 //--------------------------------------------------------------------

CLASSNAME::CLASSNAME()
{
  //DIAL DECLARATIONS HERE

  //generated

   strcpy(_b_prot_flagTYPENAME,CLASS_STRING);
strcpy(_b_prot_flagREAD,"b_prot_flag_READ");
strcpy(_b_prot_flagWRITE,"b_prot_flag_WRITE");
strcpy(_b_prot_flagEXEC,"b_prot_flag_EXEC");
strcpy(_b_prot_flagALL,"b_prot_flag_ALL");
strcpy(_b_prot_flagNONE,"b_prot_flag_NONE");
}

//--------------------------------------------------------------------
b_param *b_prot_flag::b_prot_flagREAD()
{
   return &_b_prot_flagREAD;
}

b_param *b_prot_flag::b_prot_flagWRITE()
{
   return &_b_prot_flagWRITE;
}

b_param *b_prot_flag::b_prot_flagEXEC()
{
   return &_b_prot_flagEXEC;
}

b_param *b_prot_flag::b_prot_flagALL()
{
   return &_b_prot_flagALL;
}

b_param *b_prot_flag::b_prot_flagNONE()
{
   return &_b_prot_flagNONE;
}

//--------------------------------------------------------------------
//---------------------------------------------------------------------------
//type name return method

b_param *CLASSNAME::typeName()
{
  return &_b_prot_flagTYPENAME;
}

//---------------------------------------------------------------------------
//---------------------------------------------------------------------------
int CLASSNAME::distanceFromBase()
{
  return CLASSPARENT::distanceFromBase() +1;
}


//---------------------------------------------------------------------------
void CLASSNAME::typeList(b_param list[], int num)
{
  strcpy(list[num],(char *) typeName());
  CLASSPARENT::typeList(list,num+1);
}
//--------------------------------------------------------------------
  void *CLASSNAME::access(b_param data[])
{
  if (strcmp(data[0],(char *)typeName())!=0)
    return CLASSPARENT::access(data);

  //ACCESS CODE
b_prot_flag_read = 0;
b_prot_flag_write = 0;
b_prot_flag_exec = 0;
b_prot_flag_all = 0;
b_prot_flag_none = 0;
   int dataPTR =0;


   dataPTR++;
if (strcmp(data[dataPTR],_b_prot_flagREAD)==0)
      b_prot_flag_read = 1;
   else if (strcmp(data[dataPTR],_b_prot_flagWRITE)==0)
      b_prot_flag_write = 1;
   else if (strcmp(data[dataPTR],_b_prot_flagEXEC)==0)
      b_prot_flag_exec = 1;
   else if (strcmp(data[dataPTR],_b_prot_flagALL)==0)
      b_prot_flag_all = 1;
   else if (strcmp(data[dataPTR],_b_prot_flagNONE)==0)
      b_prot_flag_none = 1;
  else
    {
      cerr<<"Error: Unknown setting for the "
          <<"HVAL"
          <<" dial of the data object "
          <<CLASS_STRING
          <<". "<<endl
          <<"The offending string is : "
          <<data[dataPTR]
          <<endl;
      exit(1);
    }

if (b_prot_flag_read==1)
{

 _theVariable= PROT_READ;
 
}

if (b_prot_flag_write==1)
{

 _theVariable= PROT_WRITE;
 
}

if (b_prot_flag_exec==1)
{

 _theVariable= PROT_EXEC;
 
}

if (b_prot_flag_all==1)
{

 _theVariable= PROT_READ | PROT_WRITE | PROT_EXEC;
 
}

if (b_prot_flag_none==1)
{

 _theVariable= PROT_NONE;
 
}
   return &_theVariable;
}

//--------------------------------------------------------------------
  int CLASSNAME::commit(b_param tname)
{
  if (strcmp(tname,(char *)typeName())!=0)
    return CLASSPARENT::commit(tname);
  //COMMIT CODE HERE
//generated
   return 0;
}

//--------------------------------------------------------------------
  int CLASSNAME::cleanup(b_param tname)
{
  if (strcmp(tname,(char *)typeName())!=0)
    return CLASSPARENT::cleanup(tname);
      
  //CLEANUP CODE
//generated
   return 0;
}

//--------------------------------------------------------------------
int CLASSNAME::numDials(b_param tname)
{
  if (!strcmp(tname,(char *)typeName()))
    return NUMBER_OF_DIALS;
  else return CLASSPARENT::numDials(tname);
      
}


//---------------------------------------------------------------------------
int CLASSNAME::numItems(b_param tname,int dialNumber)
{
  if (strcmp(tname,(char *)typeName())!=0)
    return CLASSPARENT::numItems(tname,dialNumber);
  switch (dialNumber)
    {
      //NUMITEMS SWITCH CASES HERE
      //generated

   case 1:
      return 5;
      break;
//---------------------------------------------------------------------------
      //end generated

    default:
      cerr<<"Error, invalid dial number passed to "
          <<CLASS_STRING<<"::numItems\n"
          <<"Please check declaration files.  Dial number passed was "
          <<dialNumber<<endl;
      exit(1);
    }
  return 0;
}

//---------------------------------------------------------------------------
b_param *CLASSNAME::paramName(b_param tname,
                                   int dialNumber,
                                   int position)

{
  if (strcmp(tname,(char *)typeName())!=0)
    return CLASSPARENT::paramName(tname,dialNumber,position);
  
  switch (dialNumber)
    {
      //PARAMNAME SWITCH CASES HERE
      //generated

case 1:
 switch (position)
   {
      case 1:
         return b_prot_flagREAD();
         break;
      case 2:
         return b_prot_flagWRITE();
         break;
      case 3:
         return b_prot_flagEXEC();
         break;
      case 4:
         return b_prot_flagALL();
         break;
      case 5:
         return b_prot_flagNONE();
         break;

      default:
          cerr<<"Error, invalid position number passed to "
              <<CLASS_STRING<<"::paramName\n"
              <<"Please check declaration files.  Dial number passed was"
              <<dialNumber<<" position "<<position<<".\n";
          exit(1);
   }
   break;
    default:
      cerr<<"Error, invalid dial number passed to "
          <<CLASS_STRING<<"::paramName\n"
          <<"Please check declaration files.  Dial number passed was "
          <<dialNumber<<endl;
      exit(1);

    }
  return NULL;
}

//---------------------------------------------------------------------------
