/*
   b_ptr_tm.h   Generated by the Ballista(tm) Project data object compiler
   Copyright (C) 1998-2001  Carnegie Mellon University

   This program is free software; you can redistribute it and/or
   modify it under the terms of the GNU General Public License
   as published by the Free Software Foundation; either version 2
   of the License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

   File generated Friday, December 17 at 06:05 PM CST

TITLE
   b_ptr_tm.h
*/

//include control
#ifndef B_PTR_TM_H
#define B_PTR_TM_H
#include <errno.h>
#include <iostream.h>
#include <stdio.h>
#include <stdlib.h>
#include <stream.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include "bTypes.h"


#include <time.h>
#include "bTypes.h"
#include "b_ptr_buf.h"
#define StructtmPtr struct tm*
#define CLASSTYPE StructtmPtr
#define CLASSNAME b_ptr_tm
#define CLASS_STRING "b_ptr_tm"
#define CLASSPARENT b_ptr_buf
#define NUMBER_OF_DIALS 1


class CLASSNAME:public CLASSPARENT
{
private:
  //CLASS DIAL SETTING STRING VARIABLES
  b_param _b_ptr_tmTYPENAME;
b_param _b_ptr_tmLOCALTIME_R_NOW;
int b_ptr_tm_localtime_r_now;
b_param _b_ptr_tmGMTIME_R_NOW;
int b_ptr_tm_gmtime_r_now;
b_param _b_ptr_tmALL_ZERO;
int b_ptr_tm_all_zero;
b_param _b_ptr_tmALL_TOP_RANGE;
int b_ptr_tm_all_top_range;
b_param _b_ptr_tmALL_OVERFLOW;
int b_ptr_tm_all_overflow;
b_param _b_ptr_tmALL_MAX;
int b_ptr_tm_all_max;
b_param _b_ptr_tmALL_MIN;
int b_ptr_tm_all_min;
  //TYPE VARIABLE TO SAVE VALUE FOR DESTRUCTION
  CLASSTYPE _theVariable;

 public:
  //CLASS DIAL SETTING STRING ACCESS METHODS
b_param *b_ptr_tmLOCALTIME_R_NOW();
b_param *b_ptr_tmGMTIME_R_NOW();
b_param *b_ptr_tmALL_ZERO();
b_param *b_ptr_tmALL_TOP_RANGE();
b_param *b_ptr_tmALL_OVERFLOW();
b_param *b_ptr_tmALL_MAX();
b_param *b_ptr_tmALL_MIN();
  //CLASS CONSTRUCTOR
  CLASSNAME();

public:
  //Mandatory Methods
  b_param *typeName();           //returns the type of parameter
  virtual void *access(b_param data[]);
  virtual int commit(b_param tname);
  virtual int cleanup(b_param tname);
  
  virtual int numDials(b_param tname);
  virtual int numItems(b_param tname,int dialNumber);
  virtual b_param *paramName(b_param tname,int dialNumber, int position);

  virtual int distanceFromBase();
  virtual void typeList(b_param list[],int num);
  
};



#endif      //CLASSNAME_H
