/*
   b_ptr_sem_t.h   Generated by the Ballista(tm) Project data object compiler
   Copyright (C) 1998-2001  Carnegie Mellon University

   This program is free software; you can redistribute it and/or
   modify it under the terms of the GNU General Public License
   as published by the Free Software Foundation; either version 2
   of the License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

   File generated Friday, December 17 at 06:09 PM CST

TITLE
   b_ptr_sem_t.h
*/

//include control
#ifndef B_PTR_SEM_T_H
#define B_PTR_SEM_T_H
#include <errno.h>
#include <iostream.h>
#include <stdio.h>
#include <stdlib.h>
#include <stream.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include "bTypes.h"

#include <semaphore.h>
#define structsemtptr sem_t*
#include <fcntl.h>
#include "b_ptr_buf.h"
#define CLASSTYPE structsemtptr
#define CLASSNAME b_ptr_sem_t
#define CLASS_STRING "b_ptr_sem_t"
#define CLASSPARENT b_ptr_buf
#define NUMBER_OF_DIALS 1


class CLASSNAME:public CLASSPARENT
{
private:
  //CLASS DIAL SETTING STRING VARIABLES
  b_param _b_ptr_sem_tTYPENAME;
b_param _b_ptr_sem_tOPEN;
int b_ptr_sem_t_open;
b_param _b_ptr_sem_tCLOSED;
int b_ptr_sem_t_closed;
b_param _b_ptr_sem_tINIT;
int b_ptr_sem_t_init;
b_param _b_ptr_sem_tDESTROYED;
int b_ptr_sem_t_destroyed;
b_param _b_ptr_sem_tUNLINKED;
int b_ptr_sem_t_unlinked;
  //TYPE VARIABLE TO SAVE VALUE FOR DESTRUCTION
  CLASSTYPE _theVariable;

 public:
  //CLASS DIAL SETTING STRING ACCESS METHODS
b_param *b_ptr_sem_tOPEN();
b_param *b_ptr_sem_tCLOSED();
b_param *b_ptr_sem_tINIT();
b_param *b_ptr_sem_tDESTROYED();
b_param *b_ptr_sem_tUNLINKED();
  //CLASS CONSTRUCTOR
  CLASSNAME();

public:
  //Mandatory Methods
  b_param *typeName();           //returns the type of parameter
  virtual void *access(b_param data[]);
  virtual int commit(b_param tname);
  virtual int cleanup(b_param tname);
  
  virtual int numDials(b_param tname);
  virtual int numItems(b_param tname,int dialNumber);
  virtual b_param *paramName(b_param tname,int dialNumber, int position);

  virtual int distanceFromBase();
  virtual void typeList(b_param list[],int num);
  
};



#endif      //CLASSNAME_H
