/*
   b_ptr_itimerspec.h   Generated by the Ballista(tm) Project data object compiler
   Copyright (C) 1998-2001  Carnegie Mellon University

   This program is free software; you can redistribute it and/or
   modify it under the terms of the GNU General Public License
   as published by the Free Software Foundation; either version 2
   of the License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

   File generated Friday, December 17 at 06:06 PM CST

TITLE
   b_ptr_itimerspec.h
*/

//include control
#ifndef B_PTR_ITIMERSPEC_H
#define B_PTR_ITIMERSPEC_H
#include <errno.h>
#include <iostream.h>
#include <stdio.h>
#include <stdlib.h>
#include <stream.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include "bTypes.h"

#include <time.h>
#include "bTypes.h"
#include "b_ptr_buf.h"
#define structitimerspecptr struct itimerspec*
#define CLASSTYPE structitimerspecptr
#define CLASSNAME b_ptr_itimerspec
#define CLASS_STRING "b_ptr_itimerspec"
#define CLASSPARENT b_ptr_buf
#define NUMBER_OF_DIALS 2


class CLASSNAME:public CLASSPARENT
{
private:
  //CLASS DIAL SETTING STRING VARIABLES
  b_param _b_ptr_itimerspecTYPENAME;
b_param _b_ptr_itimerspecINTERVAL_REALTIME;
int b_ptr_itimerspec_interval_realtime;
b_param _b_ptr_itimerspecINTERVAL_GETTIME;
int b_ptr_itimerspec_interval_gettime;
b_param _b_ptr_itimerspecINTERVAL_ZERO;
int b_ptr_itimerspec_interval_zero;
b_param _b_ptr_itimerspecINTERVAL_NEG_ONE_NS;
int b_ptr_itimerspec_interval_neg_one_ns;
b_param _b_ptr_itimerspecINTERVAL_ILL;
int b_ptr_itimerspec_interval_ill;
b_param _b_ptr_itimerspecINTERVAL_NEG_ONE_SEC;
int b_ptr_itimerspec_interval_neg_one_sec;
b_param _b_ptr_itimerspecINTERVAL_MIN;
int b_ptr_itimerspec_interval_min;
b_param _b_ptr_itimerspecINTERVAL_MAX;
int b_ptr_itimerspec_interval_max;
b_param _b_ptr_itimerspecINTERVAL_MIXED_1;
int b_ptr_itimerspec_interval_mixed_1;
b_param _b_ptr_itimerspecINTERVAL_MIXED_2;
int b_ptr_itimerspec_interval_mixed_2;
b_param _b_ptr_itimerspecVALUE_REALTIME;
int b_ptr_itimerspec_value_realtime;
b_param _b_ptr_itimerspecVALUE_GETTIME;
int b_ptr_itimerspec_value_gettime;
b_param _b_ptr_itimerspecVALUE_ZERO;
int b_ptr_itimerspec_value_zero;
b_param _b_ptr_itimerspecVALUE_NEG_ONE_NS;
int b_ptr_itimerspec_value_neg_one_ns;
b_param _b_ptr_itimerspecVALUE_ILL;
int b_ptr_itimerspec_value_ill;
b_param _b_ptr_itimerspecVALUE_NEG_ONE_SEC;
int b_ptr_itimerspec_value_neg_one_sec;
b_param _b_ptr_itimerspecVALUE_MIN;
int b_ptr_itimerspec_value_min;
b_param _b_ptr_itimerspecVALUE_MAX;
int b_ptr_itimerspec_value_max;
b_param _b_ptr_itimerspecVALUE_MIXED_1;
int b_ptr_itimerspec_value_mixed_1;
b_param _b_ptr_itimerspecVALUE_MIXED_2;
int b_ptr_itimerspec_value_mixed_2;
  //TYPE VARIABLE TO SAVE VALUE FOR DESTRUCTION
  CLASSTYPE _theVariable;

 public:
  //CLASS DIAL SETTING STRING ACCESS METHODS
b_param *b_ptr_itimerspecINTERVAL_REALTIME();
b_param *b_ptr_itimerspecINTERVAL_GETTIME();
b_param *b_ptr_itimerspecINTERVAL_ZERO();
b_param *b_ptr_itimerspecINTERVAL_NEG_ONE_NS();
b_param *b_ptr_itimerspecINTERVAL_ILL();
b_param *b_ptr_itimerspecINTERVAL_NEG_ONE_SEC();
b_param *b_ptr_itimerspecINTERVAL_MIN();
b_param *b_ptr_itimerspecINTERVAL_MAX();
b_param *b_ptr_itimerspecINTERVAL_MIXED_1();
b_param *b_ptr_itimerspecINTERVAL_MIXED_2();
b_param *b_ptr_itimerspecVALUE_REALTIME();
b_param *b_ptr_itimerspecVALUE_GETTIME();
b_param *b_ptr_itimerspecVALUE_ZERO();
b_param *b_ptr_itimerspecVALUE_NEG_ONE_NS();
b_param *b_ptr_itimerspecVALUE_ILL();
b_param *b_ptr_itimerspecVALUE_NEG_ONE_SEC();
b_param *b_ptr_itimerspecVALUE_MIN();
b_param *b_ptr_itimerspecVALUE_MAX();
b_param *b_ptr_itimerspecVALUE_MIXED_1();
b_param *b_ptr_itimerspecVALUE_MIXED_2();
  //CLASS CONSTRUCTOR
  CLASSNAME();

public:
  //Mandatory Methods
  b_param *typeName();           //returns the type of parameter
  virtual void *access(b_param data[]);
  virtual int commit(b_param tname);
  virtual int cleanup(b_param tname);
  
  virtual int numDials(b_param tname);
  virtual int numItems(b_param tname,int dialNumber);
  virtual b_param *paramName(b_param tname,int dialNumber, int position);

  virtual int distanceFromBase();
  virtual void typeList(b_param list[],int num);
  
};



#endif      //CLASSNAME_H
