/*
   b_ptr_sigevent.h   Generated by the Ballista(tm) Project data object compiler
   Copyright (C) 1998-2001  Carnegie Mellon University

   This program is free software; you can redistribute it and/or
   modify it under the terms of the GNU General Public License
   as published by the Free Software Foundation; either version 2
   of the License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

   File generated Friday, December 17 at 06:06 PM CST

TITLE
   b_ptr_sigevent.h
*/

//include control
#ifndef B_PTR_SIGEVENT_H
#define B_PTR_SIGEVENT_H
#include <errno.h>
#include <iostream.h>
#include <stdio.h>
#include <stdlib.h>
#include <stream.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include "bTypes.h"

#include <signal.h>
#include "b_ptr_buf.h"
#define structsigeventptr struct sigevent*
#define CLASSTYPE structsigeventptr
#define CLASSNAME b_ptr_sigevent
#define CLASS_STRING "b_ptr_sigevent"
#define CLASSPARENT b_ptr_buf
#define NUMBER_OF_DIALS 2


class CLASSNAME:public CLASSPARENT
{
private:
  //CLASS DIAL SETTING STRING VARIABLES
  b_param _b_ptr_sigeventTYPENAME;
b_param _b_ptr_sigeventNOTIFY_ZERO;
int b_ptr_sigevent_notify_zero;
b_param _b_ptr_sigeventNOTIFY_MAXINT;
int b_ptr_sigevent_notify_maxint;
b_param _b_ptr_sigeventNOTIFY_MININT;
int b_ptr_sigevent_notify_minint;
b_param _b_ptr_sigeventNOTIFY_NEGONE;
int b_ptr_sigevent_notify_negone;
b_param _b_ptr_sigeventNOTIFY_ONE;
int b_ptr_sigevent_notify_one;
b_param _b_ptr_sigeventNOTIFY_NONE;
int b_ptr_sigevent_notify_none;
b_param _b_ptr_sigeventNOTIFY_SIGNAL;
int b_ptr_sigevent_notify_signal;
b_param _b_ptr_sigeventSIGABRT;
int b_ptr_sigevent_sigabrt;
b_param _b_ptr_sigeventSIGINT;
int b_ptr_sigevent_sigint;
b_param _b_ptr_sigeventSIGILL;
int b_ptr_sigevent_sigill;
b_param _b_ptr_sigeventSIGSEGV;
int b_ptr_sigevent_sigsegv;
b_param _b_ptr_sigeventSIGRTMIN;
int b_ptr_sigevent_sigrtmin;
b_param _b_ptr_sigeventSIGRTMAX;
int b_ptr_sigevent_sigrtmax;
b_param _b_ptr_sigeventMAXINT;
int b_ptr_sigevent_maxint;
b_param _b_ptr_sigeventMININT;
int b_ptr_sigevent_minint;
b_param _b_ptr_sigeventZERO;
int b_ptr_sigevent_zero;
b_param _b_ptr_sigeventONE;
int b_ptr_sigevent_one;
b_param _b_ptr_sigeventNEGONE;
int b_ptr_sigevent_negone;
  //TYPE VARIABLE TO SAVE VALUE FOR DESTRUCTION
  CLASSTYPE _theVariable;

 public:
  //CLASS DIAL SETTING STRING ACCESS METHODS
b_param *b_ptr_sigeventNOTIFY_ZERO();
b_param *b_ptr_sigeventNOTIFY_MAXINT();
b_param *b_ptr_sigeventNOTIFY_MININT();
b_param *b_ptr_sigeventNOTIFY_NEGONE();
b_param *b_ptr_sigeventNOTIFY_ONE();
b_param *b_ptr_sigeventNOTIFY_NONE();
b_param *b_ptr_sigeventNOTIFY_SIGNAL();
b_param *b_ptr_sigeventSIGABRT();
b_param *b_ptr_sigeventSIGINT();
b_param *b_ptr_sigeventSIGILL();
b_param *b_ptr_sigeventSIGSEGV();
b_param *b_ptr_sigeventSIGRTMIN();
b_param *b_ptr_sigeventSIGRTMAX();
b_param *b_ptr_sigeventMAXINT();
b_param *b_ptr_sigeventMININT();
b_param *b_ptr_sigeventZERO();
b_param *b_ptr_sigeventONE();
b_param *b_ptr_sigeventNEGONE();
  //CLASS CONSTRUCTOR
  CLASSNAME();

public:
  //Mandatory Methods
  b_param *typeName();           //returns the type of parameter
  virtual void *access(b_param data[]);
  virtual int commit(b_param tname);
  virtual int cleanup(b_param tname);
  
  virtual int numDials(b_param tname);
  virtual int numItems(b_param tname,int dialNumber);
  virtual b_param *paramName(b_param tname,int dialNumber, int position);

  virtual int distanceFromBase();
  virtual void typeList(b_param list[],int num);
  
};



#endif      //CLASSNAME_H
