/*
   b_ptr_stat.h   Generated by the Ballista(tm) Project data object compiler
   Copyright (C) 1998-2001  Carnegie Mellon University

   This program is free software; you can redistribute it and/or
   modify it under the terms of the GNU General Public License
   as published by the Free Software Foundation; either version 2
   of the License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

   File generated Saturday, December 18 at 10:20 AM CST

TITLE
   b_ptr_stat.h
*/

//include control
#ifndef B_PTR_STAT_H
#define B_PTR_STAT_H
#include <errno.h>
#include <iostream.h>
#include <stdio.h>
#include <stdlib.h>
#include <stream.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include "bTypes.h"

#define structStatptr struct stat *
#include <sys/stat.h>
#include <fcntl.h>
#include <sys/types.h>
#include <errno.h>
#include "b_ptr_buf.h"
#define CLASSTYPE structStatptr
#define CLASSNAME b_ptr_stat
#define CLASS_STRING "b_ptr_stat"
#define CLASSPARENT b_ptr_buf
#define NUMBER_OF_DIALS 1


class CLASSNAME:public CLASSPARENT
{
private:
  //CLASS DIAL SETTING STRING VARIABLES
  b_param _b_ptr_statTYPENAME;
b_param _b_ptr_statZEROS;
int b_ptr_stat_zeros;
b_param _b_ptr_statNEG1S;
int b_ptr_stat_neg1s;
b_param _b_ptr_statMAX;
int b_ptr_stat_max;
b_param _b_ptr_statFILE_SH;
int b_ptr_stat_file_sh;
b_param _b_ptr_statFILE_PASSWD;
int b_ptr_stat_file_passwd;
b_param _b_ptr_statFILE_TEST;
int b_ptr_stat_file_test;
  //TYPE VARIABLE TO SAVE VALUE FOR DESTRUCTION
  CLASSTYPE _theVariable;

 public:
  //CLASS DIAL SETTING STRING ACCESS METHODS
b_param *b_ptr_statZEROS();
b_param *b_ptr_statNEG1S();
b_param *b_ptr_statMAX();
b_param *b_ptr_statFILE_SH();
b_param *b_ptr_statFILE_PASSWD();
b_param *b_ptr_statFILE_TEST();
  //CLASS CONSTRUCTOR
  CLASSNAME();

public:
  //Mandatory Methods
  b_param *typeName();           //returns the type of parameter
  virtual void *access(b_param data[]);
  virtual int commit(b_param tname);
  virtual int cleanup(b_param tname);
  
  virtual int numDials(b_param tname);
  virtual int numItems(b_param tname,int dialNumber);
  virtual b_param *paramName(b_param tname,int dialNumber, int position);

  virtual int distanceFromBase();
  virtual void typeList(b_param list[],int num);
  
};



#endif      //CLASSNAME_H
