/*
   b_ptr_timespec.h   Generated by the Ballista(tm) Project data object compiler
   Copyright (C) 1998-2001  Carnegie Mellon University

   This program is free software; you can redistribute it and/or
   modify it under the terms of the GNU General Public License
   as published by the Free Software Foundation; either version 2
   of the License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

   File generated Friday, December 17 at 06:05 PM CST

TITLE
   b_ptr_timespec.h
*/

//include control
#ifndef B_PTR_TIMESPEC_H
#define B_PTR_TIMESPEC_H
#include <errno.h>
#include <iostream.h>
#include <stdio.h>
#include <stdlib.h>
#include <stream.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include "bTypes.h"

#include <time.h>
#include "bTypes.h"
#include "b_ptr_buf.h"
#define structtimespecptr struct timespec*
#define CLASSTYPE structtimespecptr
#define CLASSNAME b_ptr_timespec
#define CLASS_STRING "b_ptr_timespec"
#define CLASSPARENT b_ptr_buf
#define NUMBER_OF_DIALS 1


class CLASSNAME:public CLASSPARENT
{
private:
  //CLASS DIAL SETTING STRING VARIABLES
  b_param _b_ptr_timespecTYPENAME;
b_param _b_ptr_timespecREALTIME;
int b_ptr_timespec_realtime;
b_param _b_ptr_timespecTIMEOUT_ZERO;
int b_ptr_timespec_timeout_zero;
b_param _b_ptr_timespecTIMEOUT_NEG_ONE_NS;
int b_ptr_timespec_timeout_neg_one_ns;
b_param _b_ptr_timespecTIMEOUT_ILL;
int b_ptr_timespec_timeout_ill;
b_param _b_ptr_timespecTIMEOUT_NEG_ONE_SEC;
int b_ptr_timespec_timeout_neg_one_sec;
b_param _b_ptr_timespecTIMEOUT_MIN;
int b_ptr_timespec_timeout_min;
b_param _b_ptr_timespecTIMEOUT_MAX;
int b_ptr_timespec_timeout_max;
b_param _b_ptr_timespecTIMEOUT_MIXED_1;
int b_ptr_timespec_timeout_mixed_1;
b_param _b_ptr_timespecTIMEOUT_MIXED_2;
int b_ptr_timespec_timeout_mixed_2;
  //TYPE VARIABLE TO SAVE VALUE FOR DESTRUCTION
  CLASSTYPE _theVariable;

 public:
  //CLASS DIAL SETTING STRING ACCESS METHODS
b_param *b_ptr_timespecREALTIME();
b_param *b_ptr_timespecTIMEOUT_ZERO();
b_param *b_ptr_timespecTIMEOUT_NEG_ONE_NS();
b_param *b_ptr_timespecTIMEOUT_ILL();
b_param *b_ptr_timespecTIMEOUT_NEG_ONE_SEC();
b_param *b_ptr_timespecTIMEOUT_MIN();
b_param *b_ptr_timespecTIMEOUT_MAX();
b_param *b_ptr_timespecTIMEOUT_MIXED_1();
b_param *b_ptr_timespecTIMEOUT_MIXED_2();
  //CLASS CONSTRUCTOR
  CLASSNAME();

public:
  //Mandatory Methods
  b_param *typeName();           //returns the type of parameter
  virtual void *access(b_param data[]);
  virtual int commit(b_param tname);
  virtual int cleanup(b_param tname);
  
  virtual int numDials(b_param tname);
  virtual int numItems(b_param tname,int dialNumber);
  virtual b_param *paramName(b_param tname,int dialNumber, int position);

  virtual int distanceFromBase();
  virtual void typeList(b_param list[],int num);
  
};



#endif      //CLASSNAME_H
