/*
   b_signal.h   Generated by the Ballista(tm) Project data object compiler
   Copyright (C) 1998-2001  Carnegie Mellon University

   This program is free software; you can redistribute it and/or
   modify it under the terms of the GNU General Public License
   as published by the Free Software Foundation; either version 2
   of the License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

   File generated Saturday, December 18 at 10:36 AM CST

TITLE
   b_signal.h
*/

//include control
#ifndef B_SIGNAL_H
#define B_SIGNAL_H
#include <errno.h>
#include <iostream.h>
#include <stdio.h>
#include <stdlib.h>
#include <stream.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include "bTypes.h"

 #include "b_int.h"
 #include <signal.h>
 #define CLASSTYPE int
#define CLASSNAME b_signal
#define CLASS_STRING "b_signal"
#define CLASSPARENT b_int
#define NUMBER_OF_DIALS 1


class CLASSNAME:public CLASSPARENT
{
private:
  //CLASS DIAL SETTING STRING VARIABLES
  b_param _b_signalTYPENAME;
b_param _b_signalSIGILL;
int b_signal_sigill;
b_param _b_signalSIGABRT;
int b_signal_sigabrt;
b_param _b_signalSIGSEGV;
int b_signal_sigsegv;
b_param _b_signalSIGINT;
int b_signal_sigint;
b_param _b_signalSIGCHLD;
int b_signal_sigchld;
b_param _b_signalSIGRTMIN;
int b_signal_sigrtmin;
b_param _b_signalSIGRTMAX;
int b_signal_sigrtmax;
  //TYPE VARIABLE TO SAVE VALUE FOR DESTRUCTION
  CLASSTYPE _theVariable;

 public:
  //CLASS DIAL SETTING STRING ACCESS METHODS
b_param *b_signalSIGILL();
b_param *b_signalSIGABRT();
b_param *b_signalSIGSEGV();
b_param *b_signalSIGINT();
b_param *b_signalSIGCHLD();
b_param *b_signalSIGRTMIN();
b_param *b_signalSIGRTMAX();
  //CLASS CONSTRUCTOR
  CLASSNAME();

public:
  //Mandatory Methods
  b_param *typeName();           //returns the type of parameter
  virtual void *access(b_param data[]);
  virtual int commit(b_param tname);
  virtual int cleanup(b_param tname);
  
  virtual int numDials(b_param tname);
  virtual int numItems(b_param tname,int dialNumber);
  virtual b_param *paramName(b_param tname,int dialNumber, int position);

  virtual int distanceFromBase();
  virtual void typeList(b_param list[],int num);
  
};



#endif      //CLASSNAME_H
