#! /bin/sh

#  Copyright (c) International Business Machines  Corp., 2002
#
#  This program is free software;  you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY;  without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
#  the GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program;  if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

# 12/05/02  Port to bash -Robbie Williamson <robbiew@us.ibm.com>
# 02/05/03  Modified - Manoj Iyer <manjo@mail.utexas.edu> use USCTEST macros
#           fixed bugs.

##################################################################
# case 3: Do openlog(), log the messages and see whether         #
#          ident string is prepended to the mesage.              #
#                                                                #
# syslog.conf should contain:                                    #
#        *.crit           /usr/adm/critical                      #
#         daemon.info        /usr/spool/adm/syslog               #
##################################################################

syslog_case3()
{
	#set the trap to handle signals.
	trap '
		tst_resm TBROK "Testing is terminating due to a signal"
		exit 1
	' 1 2 3 6 11 15

	tst_resm TINFO  "syslog: Testing openlog() with ident strings"

	# Create the configuration file specific to this test case.
	echo "daemon.info      /var/log/messages" > /etc/syslog.conf

	#Restart syslog
	kill -1 `ps -ef | grep syslogd | grep -v grep | awk '{ print $2 }'`

        # Grep for the ident prefix: SYSLOG_CASE3 in the log file.
        oldvalue4=`grep -c "SYSLOG_CASE3" /var/log/messages`
        syslogtst 3 2>/dev/null
        if [ $? -ne 0 ]; then
                status_flag=1
                return
        fi
        sleep 2
        newvalue4=`grep -c "SYSLOG_CASE3" /var/log/messages`
        diff=$(( $newvalue4 - $oldvalue4 ))
        if [ $diff -ne 1 ]; then
                status_flag=1
        fi


}

export TST_TOTAL=1
export TST_COUNT=1
export TCID=$(basename $0)

status_flag=0

tst_resm TINFO "Do openlog(), log the messages and see whether"
tst_resm TINFO "ident string is prepended to the mesage."

#Back up /etc/syslog.conf
if ! [ -a /etc/syslog.conf ]
then
	tst_resm TBROK "/etc/syslog.conf file not found!"
else
	cp /etc/syslog.conf /etc/syslog.conf.bak03
fi

syslog_case3
if [ $status_flag -eq 0 ]
then
	tst_resm TPASS "ident string is prepended to the mesage."
else
	tst_resm TFAIL "ident string is not prepended to the mesage."
fi

#Restore syslog.conf
mv /etc/syslog.conf.bak03 /etc/syslog.conf

#Restart syslog
kill -1 `ps -ef | grep syslogd | grep -v grep | awk '{ print $2 }'`

exit $status_flag
