#! /bin/sh

#  Copyright (c) International Business Machines  Corp., 2002
#
#  This program is free software;  you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY;  without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
#  the GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program;  if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

# 12/05/02  Port to bash -Robbie Williamson <robbiew@us.ibm.com>
# 02/05/03  Modified - Manoj Iyer <manjo@mail.utexas.edu> use USCTEST macros
#           fixed bugs.

##################################################################
# case2: Test if messages of all levels are logged.              #
#        For each level, a seperate configuration file is        #
#        created and that will be used as syslog.conf file.      #
##################################################################
DEBIAN=0
#number of seconds to wait for another syslog test to complete
wait_count=60

if ! [ -e /etc/init.d/syslog ]
then
	tst_resm TINFO "/etc/init.d/syslog is not installed"
	exit 0
fi

cleanup()
{
if [ $status_flag -eq 0 ]
then
	tst_resm TPASS "messages of all levels are logged"
else
	tst_resm TFAIL "failed to log messages of all levels."
fi

#Restore syslog.conf
mv /etc/syslog.conf.ltpbak /etc/syslog.conf

#Restart syslog
tst_resm TINFO "Restart syslog"
/etc/init.d/syslog restart 2>&1 1>/dev/null 
sleep 2
if [ $DEBIAN -eq 1 ];then
 rm -f /etc/init.d/syslog
fi
exit $status_flag
}

syslog_case2()
{
	#set the trap to handle signals.
	trap '
		tst_resm TBROK "Testing is terminating due to a signal"
		status_flag=1
		cleanup
	' 1 2 3 6 11 15

	echo
	tst_resm TINFO  "syslog: Testing the messages of all levels"

	level_no=0
	level="emerg alert crit err warning notice info debug"

	tst_resm TINFO  "syslog: Testing whether messages are logged into log file"
	echo
	# check if syslogd command exits. Check for both syslogd & syslogd-ng in SLES10
	if [ -z $(which syslogd) ]
	then
	if [ -z $(which syslog-ng) ]
	then 
		tst_resm TBROK "syslogd or syslog-ng  no such command"
		status_flag=1
		cleanup
	fi
	else 
		echo "Running tests"
	fi

	#Create symlink to /etc/init.d/sysklogd for Debian
        find /etc/init.d/ |grep sysklogd 2>&1 1>/dev/null 
	RC=$?
        if [ $RC -eq 0 ]
        then
                ln -s /etc/init.d/sysklogd /etc/init.d/syslog
                DEBIAN=1
        fi

	# check if /etc/init/syslog script exists
	find /etc/init.d/ |grep syslog 2>&1 1>/dev/null 
	RC=$?
	if [ $RC -ne 0 ]
	then
		tst_resm TBROK "/etc/init.d/syslog no such script"
		status_flag=1
                cleanup

	fi
	
	for current in $level
	do
		tst_resm TINFO "Doing level: $current..."

		# Create the configuration file specific to this level
		echo "mail.$current    /var/log/maillog" >> /etc/syslog.conf

		#Restart syslog
		tst_resm TINFO "restarting syslog daemon"
		/etc/init.d/syslog restart 2>&1 1>/dev/null 
		sleep 2

		# Grepping pattern is as follows:
		# syslogtst: mail $current test.

		# check if /var/log/maillog script exists
		find /var/log/ |grep maillog 2>&1 1>/dev/null 
		RC=$?
		if [ $RC -ne 0 ]
		then
			tst_resm TBROK "/var/log/maillog no such log file"
			status_flag=1
	                cleanup

		fi

		oldvalue=`grep -c "syslogtst: mail $current test." /var/log/maillog`

		# syslogtst has to be called with additional level argument(0-7)
		syslogtst 2 $level_no 2>/dev/null
		if [ $? -ne 0 ]; then
				status_flag=1
				return
		fi
		sleep 2

		# check if /var/log/maillog script exists
		find /var/log/ |grep maillog 2>&1 1>/dev/null 
		RC=$?
		if [ $RC -ne 0 ]
		then
			tst_resm TBROK "/var/log/maillog no such log file"
			status_flag=1
	                cleanup

		fi

		newvalue=`grep -c "syslogtst: mail $current test" /var/log/maillog`
		diff=$(( $newvalue - $oldvalue ))
		if [ $diff -eq 0 ]; then
				status_flag=1
				tst_resm TINFO "***** Level $current failed *****"
		elif [ $diff -ge 1 ]; then
				tst_resm TINFO "***** Level $current passed *****"
		fi
		# Increment the level_no for next level...
		level_no=$(($level_no+1))
	done
}

export TST_TOTAL=1
export TST_COUNT=1
export TCID=$(basename $0)

RC=0
status_flag=0
tst_resm TINFO "Test if messages of all levels are logged."
tst_resm TINFO "For each level, a separate configuration file is"
tst_resm TINFO "created and that will be used as syslog.conf file."

#Back up /etc/syslog.conf
if ! [ -a /etc/syslog.conf ]
then
        tst_resm TBROK "/etc/syslog.conf not found!"
else
    while [ -a /etc/syslog.conf.ltpbak ]  #Pause if another LTP syslog test is running
    do
        if [ $(( wait_count-- )) -gt 0 ]
        then
          sleep 1
        else
          tst_resm TBROK "Another syslog test appears to be stuck, could not run"
          status_flag=1
          exit $status_flag
        fi

    done
    cp /etc/syslog.conf /etc/syslog.conf.ltpbak
fi

syslog_case2
cleanup
