#! /bin/sh

#  Copyright (c) International Business Machines  Corp., 2002
#
#  This program is free software;  you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY;  without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
#  the GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program;  if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

# 12/05/02  Port to bash -Robbie Williamson <robbiew@us.ibm.com>
# 02/05/03  Modified - Manoj Iyer <manjo@mail.utexas.edu> use USCTEST macros
#           fixed bugs.

##################################################################
# case2: Test if messages of all levels are logged.              #
#        For each level, a seperate configuration file is        #
#        created and that will be used as syslog.conf file.      #
##################################################################

syslog_case2()
{
	#set the trap to handle signals.
	trap '
		tst_resm TBROK "Testing is terminating due to a signal"
		exit 1
	' 1 2 3 6 11 15

	echo
	tst_resm TINFO  "syslog: Testing the messages of all levels"

	level_no=0
	level="emerg alert crit err warning notice info debug"

	# check if syslogd command exits.
	if [ -z $(which syslogd) ]
	then
		tst_resm TBROK "syslogd no such command"
		exit 1
	fi

	# check if /etc/init/syslog script exists
	find /etc/init.d/ -name syslog 2>&1 1>/dev/null || RC=$?
	if [ $RC -ne 0 ]
	then
		tst_resm TBROK "/etc/init.d/syslog no such script"
		exit 1
	fi
	
	for current in $level
	do
		tst_resm TINFO "Doing level: $current..."

		# Create the configuration file specific to this level
		echo "mail.$current    /var/log/maillog" >> /etc/syslog.conf

		#Restart syslog
		tst_resm TINFO "restarting syslog deamon"
		/etc/init.d/syslog restart 2>&1 1>/dev/null || RC=$?
		if [ $RC -ne 0 ]
		then
			tst_resm TBROK "failed to restart syslog deamon"
			exit 1
		fi

		# Grepping pattern is as follows:
		# syslogtst: mail $current test.

		# check if /var/log/maillog script exists
		find /var/log/ -name maillog 2>&1 1>/dev/null || RC=$?
		if [ $RC -ne 0 ]
		then
			tst_resm TBROK "/var/log/maillog no such log file"
			exit 1
		fi

		oldvalue=`grep -c "syslogtst: mail $current test." /var/log/maillog`

		# syslogtst has to be called with additional level argument(0-7)
		syslogtst 2 $level_no 2>/dev/null
		if [ $? -ne 0 ]; then
				status_flag=1
				return
		fi
		sleep 2

		# check if /var/log/maillog script exists
		find /var/log/ -name maillog 2>&1 1>/dev/null || RC=$?
		if [ $RC -ne 0 ]
		then
			tst_resm TBROK "/var/log/maillog no such log file"
			exit 1
		fi

		newvalue=`grep -c "syslogtst: mail $current test" /var/log/maillog`
		diff=$(( $newvalue - $oldvalue ))
		if [ $diff -eq 0 ]; then
				status_flag=1
				tst_resm TINFO "***** Level $current failed *****"
		elif [ $diff -ge 1 ]; then
				tst_resm TINFO "***** Level $current passed *****"
		fi
		# Increment the level_no for next level...
		level_no=$(($level_no+1))
	done
}

export TST_TOTAL=1
export TST_COUNT=1
export TCID=$(basename $0)

RC=0
status_flag=0
tst_resm TINFO "Test if messages of all levels are logged."
tst_resm TINFO "For each level, a separate configuration file is"
tst_resm TINFO "created and that will be used as syslog.conf file."

#Back up /etc/syslog.conf
if ! [ -a /etc/syslog.conf ]
then
	tst_resm TBROK "/etc/syslog.conf file not found!"
else
	cp /etc/syslog.conf /etc/syslog.conf.bak02
fi

syslog_case2
if [ $status_flag -eq 0 ]
then
	tst_resm TPASS "messages of all levels are logged"
else
	tst_resm TFAIL "failed to log messages of all levels."
fi

#Restore syslog.conf
mv /etc/syslog.conf.bak02 /etc/syslog.conf

#Restart syslog
tst_resm TINFO "Restart syslog"
/etc/init.d/syslog restart 2>&1 1>/dev/null || RC=$?
if [ $RC -ne 0 ]
then
	tst_resm TBROK "failed to restart syslog deamon"
	exit 1
fi
exit $status_flag
