#! /bin/sh

#  Copyright (c) International Business Machines  Corp., 2002
#
#  This program is free software;  you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY;  without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
#  the GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program;  if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

# 12/05/02  Port to bash -Robbie Williamson <robbiew@us.ibm.com>
# 02/05/03  Modified - Manoj Iyer <manjo@mail.utexas.edu> use USCTEST macros
#           fixed bugs.

##################################################################
# case 6: Test the logging option: LOG_NDELAY                    #
#                                                                #
#         o Do openlog() without LOG_NDELAY option.              #
#         o open a file and check the returned file descriptor   #
#           It should be 3.                                      #
#         o Now do openlog() with LOG_NDELAY option.             #
#         o open a file and check the returned file descriptor.  #
#           It should be greater than 3.                         #
##################################################################

cleanup()
{
if [ $status_flag -eq 0 ]
then
	tst_resm TPASS "file descriptor is greater than 3"
else
	tst_resm TFAIL "file descriptor is not greater than 3"
fi

#Restore syslog.conf
mv /etc/syslog.conf.ltpbak /etc/syslog.conf

#Restart syslog
tst_resm TINFO "Restart syslog"
/etc/init.d/syslog restart 2>&1 1>/dev/null 
sleep 2

exit $status_flag
}

syslog_case6()
{
	#set the trap to handle signals.
	trap '
			tst_resm TBROK "Testing is terminating due to a signal"
			status_flag=1
			cleanup
	' 1 2 3 6 11 15

	tst_resm TINFO "syslog: Testing the log option: LOG_NDELAY..."


	# check if syslogd command exits.
	if [ -z $(which syslogd) ]
	then
		tst_resm TBROK "syslogd no such command"
		status_flag=1
		cleanup
	fi

	# check if /etc/init/syslog script exists
	find /etc/init.d/ -name syslog 2>&1 1>/dev/null || RC=$?
	if [ $RC -ne 0 ]
	then
		tst_resm TBROK "/etc/init.d/syslog no such script"
		status_flag=1
		cleanup
	fi

	# Create the configuration file specific to this test case.
	# For this case, it's a dummy one. No use of it.
	echo "user.info        /var/log/messages" > /etc/syslog.conf

	#Restart syslog
	tst_resm TINFO "Restart syslog deamon"

	/etc/init.d/syslog restart 2>&1 1>/dev/null 
	sleep 2
	# Just call syslogtst. It will do everything.
	# It will return 0 to indicate that test has passed.

	syslogtst 6 2>/dev/null
	if [ $? -ne 0 ]; then
			status_flag=1
	fi
}

export TST_TOTAL=1
export TST_COUNT=1
export TCID=$(basename $0)

RC=0
status_flag=0

tst_resm TINFO " Test the logging option: LOG_NDELAY"
tst_resm TINFO " o Do openlog() without LOG_NDELAY option."
tst_resm TINFO " o open a file and check the returned file descriptor"
tst_resm TINFO "   It should be 3."
tst_resm TINFO " o Now do openlog() with LOG_NDELAY option."
tst_resm TINFO " o open a file and check the returned file descriptor."
tst_resm TINFO "   It should be greater than 3."

#Back up /etc/syslog.conf
if ! [ -a /etc/syslog.conf ]
then
        tst_resm TBROK "/etc/syslog.conf not found!"
else
    while [ -a /etc/syslog.conf.ltpbak ]  #Pause if another LTP syslog test is running
    do
      sleep 5
    done
    cp /etc/syslog.conf /etc/syslog.conf.ltpbak
fi

syslog_case6
cleanup
