#!/bin/sh
################################################################################
##                                                                            ##
## Copyright (c) International Business Machines  Corp., 2008                 ##
##                                                                            ##
## This program is free software;  you can redistribute it and#or modify      ##
## it under the terms of the GNU General Public License as published by       ##
## the Free Software Foundation; either version 2 of the License, or          ##
## (at your option) any later version.                                        ##
##                                                                            ##
## This program is distributed in the hope that it will be useful, but        ##
## WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY ##
## or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License   ##
## for more details.                                                          ##
##                                                                            ##
## You should have received a copy of the GNU General Public License          ##
## along with this program;  if not, write to the Free Software               ##
## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA    ##
##                                                                            ##
################################################################################

export TCID=ioctl01_02
export TST_TOTAL=2
export TST_COUNT=0

for tttype in `ls /dev/tty*`
do
device_no=${tttype#/dev/tty}
case "$device_no" in
[0-9]|[0-9][0-9])
    tst_resm TINFO "Testing ioctl01 with $tttype"
    ioctl01 -D $tttype
    RC=$?
    if  [ $RC -eq 0 ]
    then
     tst_resm TPASS "ioctl01 Passed with $tttype"
    else
     tst_resm TFAIL "ioctl01 Failed with $tttype"
    fi
echo;;
esac
done

for tttype in `ls /dev/tty*`
do
device_no=${tttype#/dev/tty}
case "$device_no" in
[0-9]|[0-9][0-9])
    tst_resm TINFO "Testing ioctl02 with $tttype"
    ioctl02 -D $tttype
    RC=$?
    if  [ $RC -eq 0 ]
    then
     tst_resm TPASS "ioctl02 Passed with $tttype"
    else
     tst_resm TFAIL "ioctl02 Failed with $tttype"
    fi
echo;;
esac
done
tst_exit

