#!/bin/bash

# Authenticate through the BSO firewall before building tests.

# Copyright (C) 2003-2006 IBM
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
# 02111-1307, USA.

if [ $USE_CACHE -eq 1 ];
then
	wget -q $POUNDER_CACHE > /dev/null
	if [ "$?" -eq 0 ]; then
        	echo Connected to the local test cache.  	
		rm index.html
        	exit 0
	fi

fi

# Make sure user has authenticated via BSO...
echo -en "Have you authenticated through the BSO? (Y/n) "
read f
if [ "$f" != "y" -a "$f" != "Y" -a "$f" != "" ]; then
	echo "Launching telnet to authenticate."
	telnet www.yahoo.com
fi
