# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) Linux Test Project, 2020

top_srcdir		?= ../..

include $(top_srcdir)/include/mk/env_pre.mk

LIB			:= libltpvdso.a

include $(top_srcdir)/include/mk/lib.mk
include $(top_srcdir)/include/mk/generic_leaf_target.mk
