# SPDX-License-Identifier: GPL-2.0-or-later

top_srcdir		?= ../../../..

include $(top_srcdir)/include/mk/env_pre.mk
INSTALL_DIR		:= testcases/data/lvm
INSTALL_TARGETS		:= runfile.tpl
include $(top_srcdir)/include/mk/generic_leaf_target.mk
