#!/bin/sh

# Copyright (c) 2014 Oracle and/or its affiliates. All Rights Reserved.
# Copyright (c) International Business Machines  Corp., 2006
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
# Author: Mitsuru Chinen <mitch@jp.ibm.com>

TCID=broken_ip4-dstaddr01
TST_TOTAL=1

. broken_ip4_lib.sh

tst_resm TINFO "Verify that the kernel is not crashed with receiving \
a large number of IPv4 packets whose destination address is wrong \
(destination MAC address is correct)"

tst_rhost_run -s -c "ns-icmpv4_sender -I $(tst_iface rhost) -S $rhost_addr \
	-M $(tst_hwaddr lhost) -D $lhost_addr -s 56 -t $NS_DURATION -i"

tst_resm TPASS "Test is finished successfully."

tst_exit
