# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) International Business Machines  Corp., 2001
# Copyright (c) 2021 FUJITSU LIMITED. All rights reserved.

top_srcdir		?= ../../../..

include $(top_srcdir)/include/mk/testcases.mk

CFLAGS += -I$(abs_srcdir)/../mallinfo

include $(top_srcdir)/include/mk/generic_leaf_target.mk
