###############################################################################
#                                                                            ##
# Copyright (c) Huawei Technologies Co., Ltd., 2015                          ##
#                                                                            ##
# This program is free software;  you can redistribute it and#or modify      ##
# it under the terms of the GNU General Public License as published by       ##
# the Free Software Foundation; either version 2 of the License, or          ##
# (at your option) any later version.                                        ##
#                                                                            ##
# This program is distributed in the hope that it will be useful, but        ##
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY ##
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License   ##
# for more details.                                                          ##
#                                                                            ##
# You should have received a copy of the GNU General Public License          ##
# along with this program.                                                   ##
###############################################################################

top_srcdir		?= ../../../..

include $(top_srcdir)/include/mk/testcases.mk

LDLIBS			:= $(LDLIBS) $(CAP_LIBS)

include $(top_srcdir)/include/mk/generic_leaf_target.mk
