# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) International Business Machines  Corp., 2008
# Author: Veerendra <veeren@linux.vnet.ibm.com>
# Copyright (c) 2015 Red Hat, Inc.
# Copyright (C) 2023 SUSE LLC Andrea Cervesato <andrea.cervesato@suse.com>

top_srcdir              ?= ../../../..

include $(top_srcdir)/include/mk/testcases.mk

INSTALL_TARGETS		:= *.sh

include $(top_srcdir)/include/mk/generic_leaf_target.mk
