# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2017 Red Hat, Inc.

top_srcdir		?= ../../../..

include $(top_srcdir)/include/mk/env_pre.mk

INSTALL_TARGETS		:= *.sh

include $(top_srcdir)/include/mk/generic_leaf_target.mk

