#!/bin/bash

[ -n "$show_cmds" ] && echo "/usr/bin/gpg --homedir . $*"

if /usr/bin/gpg --homedir . $* 2>err.tmp.$$ ; then
    :
else
    echo "(/usr/bin/gpg --homedir . $*) failed" >&2
    cat err.tmp.$$ >&2
    rm err.tmp.$$
    exit 1
fi
fgrep -v -f run-gpg.patterns err.tmp.$$
rm err.tmp.$$

