generate:
	../../generate.sh

all: generate

install: 
	ln -f ftp01 ../../../bin
	ln -f ftp02 ../../../bin
	ln -f ftp02_s1 ../../../bin
	ln -f ftp03 ../../../bin
	ln -f ftp04 ../../../bin
	ln -f ftp05 ../../../bin
	ln -f ftp_set_passwd ../../../bin
	ln -f ftp_setup_vsftp_conf ../../../bin

clean:
	rm -rf datafiles
