# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2014 Fujitsu Ltd.

top_srcdir		?= ../../..

include $(top_srcdir)/include/mk/env_pre.mk

include $(top_srcdir)/include/mk/generic_trunk_target.mk
