#! /bin/sh
# $OpenLDAP: pkg/ldap/tests/scripts/passwd-search,v 1.2.8.3 2001/12/04 17:40:57 kurt Exp $

if test $# -eq 0 ; then
	SRCDIR="."
else
	SRCDIR=$1; shift
fi
if test $# -eq 1 ; then
	BACKEND=$1; shift
fi

echo "running defines.sh $SRCDIR $BACKEND"
. $SRCDIR/scripts/defines.sh

echo "Cleaning up in $DBDIR..."

rm -f $DBDIR/[!C]*

echo "Starting slapd on TCP/IP port $PORT..."
$SLAPD -f $PASSWDCONF -h $MASTERURI -d $LVL $TIMING > $MASTERLOG 2>&1 &
PID=$!

echo "Testing slapd searching..."
for i in 0 1 2 3 4 5; do
	$LDAPSEARCH -L -b "$BASEDN" -h localhost -p $PORT \
		'objectclass=*' > /dev/null 2>&1
	RC=$?
	if test $RC = 1 ; then
		echo "Waiting 5 seconds for slapd to start..."
		sleep 5
	fi
done

if test $RC != 0 ; then
	echo "ldapsearch failed!"
	kill -HUP $PID
	exit $RC
fi

cat /dev/null > $TESTOUT

echo "Testing base suffix searching..."
$LDAPSEARCH -L -S "" -b "$BASEDN" -s base -h localhost -p $PORT \
	'(objectclass=*)' >> $TESTOUT 2>&1
if test $RC != 0 ; then
	echo "ldapsearch failed!"
	kill -HUP $PID
	exit $RC
fi

echo " ------------ " >> $TESTOUT

echo "Testing user searching..."
$LDAPSEARCH -L -S "" -b "uid=root,$BASEDN" -s base -h localhost -p $PORT \
	'(objectclass=*)' >> $TESTOUT 2>&1
if test $RC != 0 ; then
	echo "ldapsearch failed!"
	kill -HUP $PID
	exit $RC
fi

echo " ------------ " >> $TESTOUT

echo "Testing exact searching..."
$LDAPSEARCH -L -S "" -b "$BASEDN" -h localhost -p $PORT \
	'(uid=root)' >> $TESTOUT 2>&1
if test $RC != 0 ; then
	echo "ldapsearch failed!"
	kill -HUP $PID
	exit $RC
fi

echo " ------------ " >> $TESTOUT

echo "Testing OR searching..."
$LDAPSEARCH -L -S "" -b "$BASEDN" -h localhost -p $PORT \
	'(|(objectclass=person)(cn=root))' >> $TESTOUT 2>&1
if test $RC != 0 ; then
	echo "ldapsearch failed!"
	kill -HUP $PID
	exit $RC
fi

echo " ------------ " >> $TESTOUT

echo "Testing AND searching..."
$LDAPSEARCH -L -S "" -b "$BASEDN" -h localhost -p $PORT \
	'(&(objectclass=person)(cn=root))' >> $TESTOUT 2>&1
if test $RC != 0 ; then
	echo "ldapsearch failed!"
	kill -HUP $PID
	exit $RC
fi

kill -HUP $PID

echo "Assuming everything is fine."
#echo "Comparing results"
#$CMP $TESTOUT $SEARCHOUTMASTER
#if test $? != 0 ; then
#	echo "Comparison failed"
#	exit 1
#fi

echo ">>>>> Test succeeded"


exit 0
