#! /bin/sh
# $OpenLDAP: pkg/ldap/tests/scripts/test010-passwd,v 1.1.2.4 2000/10/11 02:36:34 kurt Exp $

if test $# -eq 0 ; then
	SRCDIR="."
else
	SRCDIR=$1; shift
fi
if test $# -eq 1 ; then
	BACKEND=$1; shift
fi

echo "running defines.sh $SRCDIR $BACKEND"
. $SRCDIR/scripts/defines.sh

echo "Cleaning up in $DBDIR..."

rm -f $DBDIR/[!C]*

echo "Starting slapd on TCP/IP port $PORT..."
$SLAPD -f $PWCONF -h $MASTERURI -d $LVL $TIMING > $MASTERLOG 2>&1 &
PID=$!

echo "Using ldapsearch to check that slapd is running..."
for i in 0 1 2 3 4 5; do
	$LDAPSEARCH -s base -b "$MONITOR" -h localhost -p $PORT \
		'objectclass=*' > /dev/null 2>&1
	RC=$?
	if test $RC = 1 ; then
		echo "Waiting 5 seconds for slapd to start..."
		sleep 5
	fi
done

echo "Using ldapadd to populate the database..."
$LDAPADD -D "$MANAGERDN" -h localhost -p $PORT -w $PASSWD < \
	$LDIFPASSWD > $TESTOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldapadd failed ($RC)!"
	kill -HUP $PID
	exit $RC
fi

echo > $SEARCHOUT
echo > $TESTOUT

echo "Using ldapsearch to verify population ..."
echo "++ Initial search" >> $SEARCHOUT
$LDAPSEARCH -h localhost -p $PORT \
	-D "$MANAGERDN" -w $PASSWD \
	-b "$BASEDN" \
	'objectclass=*' >> $SEARCHOUT 2>&1

echo "Using ldappasswd (PASS 1)  ..."
echo "Pass 1" >> $TESTOUT
$LDAPPASSWD -h localhost -p $PORT \
	-w secret -s newsecret \
	-D "cn=md5, $BASEDN" >> $TESTOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldappasswd failed ($RC)!"
	kill -HUP $PID
	exit $RC
fi
$LDAPPASSWD -h localhost -p $PORT \
	-w $PASSWD -s newsecret \
	-D $MANAGERDN "cn=smd5, $BASEDN" >> $TESTOUT 2>&1
if test $RC != 0 ; then
	echo "ldappasswd failed ($RC)!"
	kill -HUP $PID
	exit $RC
fi
$LDAPPASSWD -h localhost -p $PORT \
	-w secret -s newsecret \
	-D "cn=sha, $BASEDN" >> $TESTOUT 2>&1
if test $RC != 0 ; then
	echo "ldappasswd failed ($RC)!"
	kill -HUP $PID
	exit $RC
fi
$LDAPPASSWD -h localhost -p $PORT \
	-w secret -s newsecret \
	-D "cn=ssha, $BASEDN" >> $TESTOUT 2>&1
if test $RC != 0 ; then
	echo "ldappasswd failed ($RC)!"
	kill -HUP $PID
	exit $RC
fi

echo "" >> $TESTOUT
echo "Pass 2" >> $TESTOUT
echo "Using ldappasswd (PASS 2)  ..."
$LDAPPASSWD -h localhost -p $PORT \
	-w newsecret \
	-D "cn=md5, $BASEDN" >> $TESTOUT 2>&1
if test $RC != 0 ; then
	echo "ldappasswd failed ($RC)!"
	kill -HUP $PID
	exit $RC
fi
$LDAPPASSWD -h localhost -p $PORT \
	-w newsecret \
	-D "cn=smd5, $BASEDN" >> $TESTOUT 2>&1
if test $RC != 0 ; then
	echo "ldappasswd failed ($RC)!"
	kill -HUP $PID
	exit $RC
fi
$LDAPPASSWD -h localhost -p $PORT \
	-w newsecret \
	-D "cn=sha, $BASEDN" >> $TESTOUT 2>&1
if test $RC != 0 ; then
	echo "ldappasswd failed ($RC)!"
	kill -HUP $PID
	exit $RC
fi
$LDAPPASSWD -h localhost -p $PORT \
	-w newsecret \
	-D "cn=ssha, $BASEDN" >> $TESTOUT 2>&1
if test $RC != 0 ; then
	echo "ldappasswd failed ($RC)!"
	kill -HUP $PID
	exit $RC
fi

kill -HUP $PID

echo ">>>>> Test succeeded"

exit 0
