# Copyright (c) 2004, Intel Corporation. All rights reserved.
# Created by:  adam.li@intel.com
# This file is licensed under the GPL license.  For the full content
# of this license, see the COPYING file at the top level of this
# source tree.

CFLAGS=		-I../../../include
LDLIBS=		-lpthread -lrt
TARGETS=	pthread_cond_wait_1 pthread_cond_wait_2

all: $(TARGETS)

clean:
	-rm -f $(TARGETS)
