#!/bin/sh

set -e

TMP=${TMP:-/tmp}

if ! PROGDIR=$(dirname "$0") ; then

    if [ -x "$LTPROOT/testcases/bin/create_link" ] ; then
        PROGDIR=$LTPROOT/testcases/bin
    else
        echo "${0%##*/} : ERROR : Couldn't determine directory for \`$0'"
        exit 1
    fi

fi

cp "$PROGDIR/create_link" "$TMP"
chown root:root "$TMP/create_link"
chmod 04755 "$TMP/create_link"
