# SPDX-License-Identifier: GPL-2.0-or-later
#  Copyright (c) 2014 Oracle and/or its affiliates. All Rights Reserved.

top_srcdir		?= ../../../..

include $(top_srcdir)/include/mk/testcases.mk

include $(top_srcdir)/include/mk/generic_leaf_target.mk
