#!/bin/bash

# Runs the LTP suite

# Copyright (C) 2003-2006 IBM
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
# 02111-1307, USA.

LTPRUNALL=`ls $POUNDER_TMPDIR/opt/ltp/runltp`

# Catch errors
LOGFILE=/proc/$$/fd/1
OLD_ERRORS=`egrep -c "FAIL  :" $LOGFILE`

"$LTPRUNALL"

if [ $? -ne 0 ]; then
	exit 255
fi

# Catch errors
NEW_ERRORS=`egrep -c "FAIL  :" $LOGFILE`
ERRORS=$(( NEW_ERRORS - OLD_ERRORS ))
if [ $ERRORS -eq 255 ]; then
        ERRORS=254
fi
exit $ERRORS
