#!/bin/sh

# Control script for time consistency tests.

# Copyright (C) 2003-2006 IBM
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
# 02111-1307, USA.


# How many errors are already here?
LOGFILE=/proc/$$/fd/1
OLD_ERRORS=`grep ^--- $LOGFILE | wc -l`

$POUNDER_HOME/timed_loop 600 "$POUNDER_SRCDIR/time_tests/inconsistency-check"
# Can we find any new errors?
NEW_ERRORS=`grep ^--- $LOGFILE | wc -l`

TOTAL_ERRORS=$(( NEW_ERRORS - OLD_ERRORS))
if [ $TOTAL_ERRORS -eq 255 ]; then
        TOTAL_ERRORS=254
fi
exit $TOTAL_ERRORS
