#
#    network/rpc/basic_tests/rpc01/datafiles Makefile.
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#    Simon Xu <xu.simon@oracle.com> Nov 8 2013
#

top_srcdir		?= ../../../../../..

include $(top_srcdir)/include/mk/env_pre.mk

INSTALL_DIR		:= testcases/data/rpc01

INSTALL_TARGETS		:= file*

include $(top_srcdir)/include/mk/generic_leaf_target.mk
