/*      -*- linux-c -*-
 *
 * (C) Copyright IBM Corp. 2004
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  This
 * file and program are licensed under a BSD style license.  See
 * the Copying file included with the OpenHPI distribution for
 * full licensing terms.
 *
 * Author(s):
 *      Steve Sherman <stevees@us.ibm.com> 
 */

/******************************************************************* 
 * WARNING! This file is auto-magically generated by:
 *          ./SaHpi2code.pl. 
 *          Do not change this file manually. Update script instead
 *******************************************************************/

#ifndef __SAHPIATCA_ENUM_UTILS_H
#define __SAHPIATCA_ENUM_UTILS_H

#ifndef __OH_UTILS_H
#warning *** Include oh_utils.h instead of individual utility header files ***
#endif

#ifdef __cplusplus
extern "C" {
#endif 

#define OH_MAX_ATCAHPILEDCOLOR 9 
extern struct oh_atcahpiledcolor_map {
  AtcaHpiLedColorT  entity_type;
  char *str;
} atcahpiledcolor_strings[OH_MAX_ATCAHPILEDCOLOR];

char * oh_lookup_atcahpiledcolor(AtcaHpiLedColorT value);
SaErrorT oh_encode_atcahpiledcolor(SaHpiTextBufferT *buffer, AtcaHpiLedColorT *type);

#define OH_MAX_ATCAHPIRESOURCELEDMODE 3 
extern struct oh_atcahpiresourceledmode_map {
  AtcaHpiResourceLedModeT  entity_type;
  char *str;
} atcahpiresourceledmode_strings[OH_MAX_ATCAHPIRESOURCELEDMODE];

char * oh_lookup_atcahpiresourceledmode(AtcaHpiResourceLedModeT value);
SaErrorT oh_encode_atcahpiresourceledmode(SaHpiTextBufferT *buffer, AtcaHpiResourceLedModeT *type);

#define OH_MAX_ATCAHPILEDBRSUPPORT 3 
extern struct oh_atcahpiledbrsupport_map {
  AtcaHpiLedBrSupportT  entity_type;
  char *str;
} atcahpiledbrsupport_strings[OH_MAX_ATCAHPILEDBRSUPPORT];

char * oh_lookup_atcahpiledbrsupport(AtcaHpiLedBrSupportT value);
SaErrorT oh_encode_atcahpiledbrsupport(SaHpiTextBufferT *buffer, AtcaHpiLedBrSupportT *type);

#define OH_MAX_ATCAHPIENTITYTYPE 13 
extern struct oh_atcahpientitytype_map {
  AtcaHpiEntityTypeT  entity_type;
  char *str;
} atcahpientitytype_strings[OH_MAX_ATCAHPIENTITYTYPE];

char * oh_lookup_atcahpientitytype(AtcaHpiEntityTypeT value);
SaErrorT oh_encode_atcahpientitytype(SaHpiTextBufferT *buffer, AtcaHpiEntityTypeT *type);


#ifdef __cplusplus
}
#endif

#endif
