/*      -*- linux-c -*-
 *
 * (C) Copyright IBM Corp. 2004
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  This
 * file and program are licensed under a BSD style license.  See
 * the Copying file included with the OpenHPI distribution for
 * full licensing terms.
 *
 * Author(s):
 *      Steve Sherman <stevees@us.ibm.com> 
 */

/******************************************************************* 
 * WARNING! This file is auto-magically generated by:
 *          ./SaHpi2code.pl. 
 *          Do not change this file manually. Update script instead
 *******************************************************************/

#ifndef __SAHPI_EVENT_ENCODE_H
#define __SAHPI_EVENT_ENCODE_H

#ifndef __OH_UTILS_H
#warning *** Include oh_utils.h instead of individual utility header files ***
#endif

#ifdef __cplusplus
extern "C" {
#endif 

#define OH_ENCODE_DELIMITER " | "
#define OH_ENCODE_DELIMITER_CHAR "|"
#define OH_ENCODE_DELIMITER_LENGTH 3

typedef struct {
    SaHpiEventCategoryT category;
    SaHpiEventStateT state;
    char *str;
} oh_categorystate_map;

#define OH_MAX_STATE_GLOBAL_STRINGS 1
extern oh_categorystate_map state_global_strings[OH_MAX_STATE_GLOBAL_STRINGS];

#define OH_MAX_STATE_STRINGS 77
extern oh_categorystate_map state_strings[OH_MAX_STATE_STRINGS];


#ifdef __cplusplus
}
#endif

#endif
