# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) International Business Machines  Corp., 2001
top_srcdir		?= ../../../..

include $(top_srcdir)/include/mk/testcases.mk

#for compat_16.mk uses the compat_16_tst.h
COMPAT_TST_16_H		:= 1

include $(abs_srcdir)/../utils/compat_16.mk
include $(top_srcdir)/include/mk/generic_leaf_target.mk
