#!/bin/sh

################################################################################
##                                                                            ##
## Copyright (c) International Business Machines  Corp., 2005                 ##
##                                                                            ##
## This program is free software;  you can redistribute it and#or modify      ##
## it under the terms of the GNU General Public License as published by       ##
## the Free Software Foundation; either version 2 of the License, or          ##
## (at your option) any later version.                                        ##
##                                                                            ##
## This program is distributed in the hope that it will be useful, but        ##
## WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY ##
## or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License   ##
## for more details.                                                          ##
##                                                                            ##
## You should have received a copy of the GNU General Public License          ##
## along with this program;  if not, write to the Free Software               ##
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA    ##
##                                                                            ##
##                                                                            ##
################################################################################
#
# File:
#   udp4-multi-diffnic04
#
# Description:
#   Verify that the kernel is not crashed with receiving and sending UDP
#   datagram at differnt NIC with the following conditions
#     - The version of IP is IPv4
#     - IPsec(ESP), transport mode
#
# Setup:
#   See testcases/network/stress/README
#
# Author:
#   Mitsuru Chinen <mitch@jp.ibm.com>
#
# History:
#	Oct 19 2005 - Created (Mitsuru Chinen)
#
#-----------------------------------------------------------------------
# Uncomment line below for debug output.
#trace_logic=${trace_logic:-"set -x"}
$trace_logic

#
# Variables -- Changed by each multi-diffnic testcase
#

# The test case ID
TCID=udp4-multi-diffnic04

# The version of IP
IP_VER=4

# true, if ipsec is used
DO_IPSEC=true

# IPsec Protocol
IPSEC_PROTO=esp

# IPsec Mode
IPSEC_MODE=transport

. udp4-multi-diffnic01
