// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (c) International Business Machines  Corp., 2001
 * Copyright (c) Linux Test Project, 2026
 */

/*
 * tse_ipcsem.h - common definitions for the IPC semaphore tests
 */

#ifndef TSE_IPCSEM_H__
#define TSE_IPCSEM_H__

#include <errno.h>
#include <sys/ipc.h>
#include <sys/sem.h>

#include "test.h"
#include "lapi/sem.h"

void cleanup(void);
void setup(void);

#define SEM_RD	0400
#define SEM_ALT	0200
#define SEM_RA	SEM_RD | SEM_ALT

#define PSEMS	10		/* a reasonable value for the number of */
				/* "primitive semaphores" per ID 	*/

#ifdef LIBIPC
key_t semkey;			/* an IPC key generated by ftok() */
#else
extern key_t semkey;	 	 /* an IPC key generated by ftok() */
#endif

void rm_sema(int sem_id);

int getipckey();
int getuserid(char *);

#endif /* libipcsem.h */
