# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2015, SUSE
# Author: Cedric Hnyda <chnyda@suse.com>

top_srcdir		?= ../../../..

include $(top_srcdir)/include/mk/testcases.mk
include $(abs_srcdir)/../Makefile.inc

INSTALL_TARGETS		:= *.sh

include $(top_srcdir)/include/mk/generic_leaf_target.mk
