# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2016 Xiao Yang <yangx.jy@cn.fujitsu.com>

top_srcdir		?= ../..

include $(top_srcdir)/include/mk/env_pre.mk

INTERNAL_LIB		:= libltpnewipc.a

include $(top_srcdir)/include/mk/lib.mk
include $(top_srcdir)/include/mk/generic_leaf_target.mk
