#!/usr/bin/perl

#    Copyright (c) International Business Machines  Corp., 2001
# 
#    This program is free software;  you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
# 
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY;  without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
#    the GNU General Public License for more details.
# 
#    You should have received a copy of the GNU General Public License
#    along with this program;  if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

#   FILE        : ltpoutput
#   DESCRIPTION : rips failures out of the output from PAN
#   HISTORY	:
#	10/20/2001 Paul Larson (plars@austin.ibm.com)
#		written

(1 + $#ARGV) || die "Usage: ltpoutput FILE\n";

$buf = "";
foreach $_ (<>) {
  $line = $_;
  $buf = $buf . $line;
  if($line =~ '<<<test_end>>>') {
    if($buf =~ "termination_id=[^0]") {
      $buf =~ tr/<>/-/;
      print $buf;
    }
    $buf = "";
  }
  if($line =~ "^pan reported") {
    print $line;
  }
}
