JAVAC ?= javac

all:
	$(JAVAC) -d ../../../classes -classpath ../../../classes BTCJ1.java
	$(JAVAC) -d ../../../classes -classpath ../../../classes BTCJ2.java
	$(JAVAC) -d ../../../classes -classpath ../../../classes BTCJ3.java
	$(JAVAC) -d ../../../classes -classpath ../../../classes BTCJ4.java
	$(JAVAC) -d ../../../classes -classpath ../../../classes BTCJ5.java
	$(JAVAC) -d ../../../classes -classpath ../../../classes BTCJ6.java
	$(JAVAC) -d ../../../classes -classpath ../../../classes BTCJ7.java
	$(JAVAC) -d ../../../classes -classpath ../../../classes BTCJ8.java
clean:
	rm -f ../../../classes/dots/basecase/*.class
