#!/bin/sh
#
#   Copyright (c) International Business Machines  Corp., 2000
#
#   This program is free software;  you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY;  without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
#   the GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this pronram;  if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
#
#
#  FILE   : rcp
#
#  PURPOSE: To test the basic functionality of the `rcp` command.
#
#  SETUP: The home directory of root on the machine exported as "RHOST"
#         MUST have a ".rhosts" file with the hostname of the machine
#         where the test is executed. 
#
#  HISTORY:
#    03/01 Robbie Williamson (robbiew@us.ibm.com)
#      -Ported
#
#
#-----------------------------------------------------------------------
# Uncomment line below for debug output.
#trace_logic=${trace_logic:-"set -x"}
$trace_logic

TC=rcp
TCbin=${TCbin:-`pwd`}
TCtmp=${TCtmp:-$TCbin/$TC$$}
TCdat=${TCdat:-$TCbin/datafiles}
LHOST=`hostname`
RHOST=${RHOST:-$LHOST}
SLEEPTIME=${SLEEPTIME:-0}
FILES=${FILES:-"bin.sm bin.med bin.lg bin.jmb"}

#-----------------------------------------------------------------------
#
# FUNCTION:  do_setup
#
#-----------------------------------------------------------------------

do_setup()
{
   $trace_logic

   rsh -n -l root $RHOST mkdir -p $TCtmp
   mkdir -p $TCtmp
}

#-----------------------------------------------------------------------
#
# FUNCTION:  do_test
#
#-----------------------------------------------------------------------

do_test()
{
   $trace_logic

   for j in $FILES
   do
      rcp $TCdat/$j $RHOST:$TCtmp/$j

      SUM1=`sum $TCdat/$j | awk '{print $1}'`
      SUM2=`rsh -n -l root $RHOST sum $TCtmp/$j | awk '{print $1}'`
      rsh -n -l root $RHOST "rm -f $TCtmp/$j"
      sleep $SLEEPTIME

      if [ $SUM1 = $SUM2 ]
      then
         echo "rcp $TCdat/$j $RHOST:$TCtmp/$j successful"
      else
         end_testcase "FAILED: wrong sum in transfer to $RHOST"
      fi
      sleep $SLEEPTIME
   done

   for j in $FILES
   do
      rcp $RHOST:$TCdat/$j $TCtmp/$j

      SUM1=`sum $TCtmp/$j | awk '{print $1}'`
      SUM2=`rsh -n -l root $RHOST sum $TCdat/$j | awk '{print $1}'`
      rm -f $TCtmp/$j
      sleep $SLEEPTIME

      if [ $SUM1 = $SUM2 ]
      then
         echo "rcp $RHOST:$TCdat/$j $TCtmp/$j successful"
      else
         end_testcase "FAILED: wrong sum in transfer to $LHOST from $RHOST"
      fi
      sleep $SLEEPTIME
   done
}

#-----------------------------------------------------------------------
#
# FUNCTION:  do_cleanup
#
#-----------------------------------------------------------------------

do_cleanup()
{
   $trace_logic

   rsh -n -l root $RHOST rmdir $TCtmp
   rmdir $TCtmp
}

#=============================================================================
# FUNCTION NAME:        end_testcase
#
# FUNCTION DESCRIPTION: Clean up
#
# PARAMETERS:           string, IF AND ONLY IF the testcase fails
#
# RETURNS:              None.
#=============================================================================

end_testcase()
{
   $trace_logic
   do_cleanup

   [ $# -eq 0 ] && { echo "Test Successful"; exit 0; }
   echo "Test Failed: $@"
   exit 1
}

#----------------------------------------------------------------------
# FUNCTION: MAIN
# PURPOSE:  To invoke the functions to perform the tasks described in
#           the prologue.
# INPUT:    None.
# OUTPUT:   A testcase run log with the results of the execution of this
#           test.
#----------------------------------------------------------------------
do_setup
do_test
end_testcase
