# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) Linux Test Project, 2021
# Author: Xie Ziyao <ziyaoxie@outlook.com>

top_srcdir		?= ../../../..

include $(top_srcdir)/include/mk/testcases.mk

include $(top_srcdir)/include/mk/generic_leaf_target.mk
