.\"
.\" $Id: doio.1,v 1.1 2000/07/27 16:59:03 alaffin Exp $
.\"
.\" Copyright (c) 2000 Silicon Graphics, Inc.  All Rights Reserved.
.\"
.\" This program is free software; you can redistribute it and/or modify it
.\" under the terms of version 2 of the GNU General Public License as
.\" published by the Free Software Foundation.
.\"
.\" This program is distributed in the hope that it would be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.\"
.\" Further, this software is distributed without any warranty that it is
.\" free of the rightful claim of any third person regarding infringement
.\" or the like.  Any license provided herein, whether implied or
.\" otherwise, applies only to this software file.  Patent licenses, if
.\" any, provided herein do not apply to combinations of this program with
.\" other software, or any other product whatsoever.
.\"
.\" You should have received a copy of the GNU General Public License along
.\" with this program; if not, write the Free Software Foundation, Inc.,
.\" 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Contact information: Silicon Graphics, Inc., 1600 Amphitheatre Pkwy,
.\" Mountain View, CA  94043, or:
.\"
.\" http://www.sgi.com
.\"
.\" For further information regarding this notice, see:
.\"
.\" http://oss.sgi.com/projects/GenInfo/NoticeExplan/
.\"
.TH doio 1 10/13/93 "UNICOS Testing"
.SH NAME
\*Cdoio\fR - Executes I/O Requests
.SH IMPLEMENTATION
All Cray Research systems
.SH SYNOPSIS
\*Cdoio\fR
.SH DESCRIPTION
.QS
Doio is one of the device-beater tools.
.PP
Options:
.RS .5i
.IP "-a"
abort on data compare errors
.IP "-n opt"
.IP "-k opt"
lockd request pipe
.IP "-K opt"
use fcntl() file locking
.IP "-r opt"
resource release interval
.IP "-s opt"
syscall log file
.IP "-w opt"
file write log file
.IP "-v"
verify writes if set
.IP "-U opt"
upanic() on varios conditions
.RE
.SH AUTHOR
Mark Maule wrote the code.
.br
Glen Overby wrote the man page.
.SH BUGS
See "Features".
