#!/bin/sh
#******************************************************************************
#   Copyright (c) International Business Machines  Corp., 2000
#
#   This program is free software;  you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY;  without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
#   the GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this pronram;  if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
#
#
#  FILE   : tcpdump
#
#  PURPOSE: To test the basic functionality of `tcpdump`.
#
#  SETUP: The "RHOST" setting should be exported to be the hostname of
#         another machine on the same subnet.  Otherwise, the hostname
#         of the tested machine will be used.
#
#  HISTORY:
#    04/17/01 Robbie Williamson (robbiew@us.ibm.com)
#      -Written
#
#-----------------------------------------------------------------------
#Uncomment line below for debug output.
#trace_logic=${trace_logic:-"set -x"}
$trace_logic

TC=tcpdump
TCtmp=${TCtmp:-/tmp/$TC$$}
RHOST=${RHOST:-`hostname`}
NUMLOOPS=${NUMLOOPS:-20}
OUTFILE=$TCtmp/tcpdump_out

#******************************************************************************
#
# FUNCTION:  do_test
# PURPOSE:   Invoke tcpdump
# INPUT:     None
#
#******************************************************************************

do_test()
{
   $trace_logic

   mkdir -p $TCtmp
   [ $? -eq 0 ] || end_testcase "mkdir -p $TCtmp failed"
   ping6 -f $RHOST > /dev/null 2>&1 &
   /usr/sbin/tcpdump -c $NUMLOOPS > $OUTFILE
   [ $? -eq 0 ] || end_testcase "Problems trying to launch tcpdump"
   grep "$RHOST\>" $OUTFILE 
   [ $? -eq 0 ] || end_testcase "$RHOST was not listed in network traffic"
   PID=`ps -ef | grep "ping6 -f $RHOST" | grep -v grep | awk '{print $2}'`
   kill -9 $PID
   rm -rf $OUTFILE
}

#=============================================================================
# FUNCTION NAME:        end_testcase
#
# FUNCTION DESCRIPTION: Clean up
#
# PARAMETERS:           string, IF AND ONLY IF the testcase fails
#
# RETURNS:              None.
#=============================================================================

end_testcase()
{
   $trace_logic
   echo "$this_file: doing $0."
   rm -rf $TCtmp
   [ $# -eq 0 ] && { echo "Test Successful"; exit 0; }
   echo "Test Failed: $@"
   exit 1
}

#-----------------------------------------------------------------------
#
# FUNCTION:  MAIN
# PURPOSE:   To invoke functions that perform the tasks as described in
#	     the design in the prolog above.
# INPUT:     See SETUP in the prolog above.
# OUTPUT:    Logged run results written to testcase run log
#
#-----------------------------------------------------------------------
do_test
end_testcase
