# SPDX-License-Identifier: GPL-2.0-or-later
#  Copyright (c) 2016 Fujitsu Ltd.
#  Author: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>

top_srcdir		?= ../../../..

epoll_wait02: LDLIBS+=-lrt

include $(top_srcdir)/include/mk/testcases.mk

include $(top_srcdir)/include/mk/generic_leaf_target.mk
