# SPDX-License-Identifier: GPL-2.0-or-later
#  Copyright (c) Jan Kara <jack@suse.cz>, 2013

top_srcdir		?= ../../../..
fanotify11: CFLAGS+=-pthread
include $(top_srcdir)/include/mk/testcases.mk

include $(top_srcdir)/include/mk/generic_leaf_target.mk
