# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) International Business Machines  Corp., 2001

top_srcdir		?= ../../../../..

include $(top_srcdir)/include/mk/env_pre.mk
include $(top_srcdir)/testcases/kernel/mem/include/libmem.mk

INTERNAL_LIB		:= libhugetlb.a

include $(top_srcdir)/include/mk/lib.mk
