/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */
/* ballistaRPC.c : Ballista RPC specification
 * Copyright (C) 1998-2001  Carnegie Mellon University
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

#include <sys/time.h>
#include <memory.h> /* for memset */
#include "ballistaRPC.h"

/* Default timeout can be changed using clnt_control() */
#ifdef HP
enum clnt_stat clnt_call2(CLIENT *rh, u_long proc, xdrproc_t xargs, caddr_t argsp, xdrproc_t xres,caddr_t resp, struct timeval timeout){
  rh->cl_ops->cl_call(rh,proc,xargs,argsp,xres,resp,timeout);
};

#endif
static struct timeval TIMEOUT = { 1000, 0 };


return_info *
get_array_3(info *argp, CLIENT *clnt)
{
	static return_info clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
#ifndef HP
	if (clnt_call(clnt, get_array,(xdrproc_t) xdr_info, (caddr_t)argp, (xdrproc_t)xdr_return_info, (caddr_t)&clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
#else
	if (clnt_call2(clnt, get_array,(xdrproc_t) xdr_info, (caddr_t)argp, (xdrproc_t)xdr_return_info, (caddr_t)&clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
#endif
	return (&clnt_res);
}

int *
send_data_3(data_from_client *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, send_data, (xdrproc_t)xdr_data_from_client, (caddr_t)argp, (xdrproc_t)xdr_int, (caddr_t)&clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}






