#!/bin/sh

# Copyright (c) 2015 Oracle and/or its affiliates. All Rights Reserved.
# Copyright (c) International Business Machines  Corp., 2005
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
# Author: Mitsuru Chinen <mitch@jp.ibm.com>

TCID="http-stress02-rmt"
TST_TOTAL=1

. test_net.sh

tst_check_cmds curl

if [ $# -ne 4 ]; then
	tst_brkm TBROK "Usage: $0 server_addr filename duration connections"
fi

server_ipaddr="$1"
filename="$2"
duration="$3"
connections="$4"

echo $server_ipaddr | grep -F ':' > /dev/null
if [ $? -eq 0 ]; then
	server_ipaddr='['$server_ipaddr']'
fi

start_epoc=$(date +%s)
while true ; do
	# Exit when the specified seconds have passed.
	current_epoc=$(date +%s)
	elapse_epoc=$(($current_epoc - $start_epoc))

	[ $elapse_epoc -ge $duration ] && break

	# Do not request the file over the specified quantity
	http_num=$(jobs | wc -l)
	if [ $http_num -ge $connections ]; then
		sleep 1
		continue;
	fi

	# Login to the server
	curl -s -g "http://$server_ipaddr/$filename" > /dev/null 2>&1 &
done

killall -qw -s SIGPIPE curl

curl -g "http://$server_ipaddr/$filename" -o /dev/null || \
	tst_brkm TBROK "Failed to get http://$server_ipaddr/$filename"

tst_exit
